### ISSUE TITLE
Clicking with Middle Mouse Executes javascript: Urls

### ISSUE THREAD

**Issue by ghost** [hackademix/noscript#104]
Even when marked as untrusted, clicking on javascript urls with middle mouse allows JS execution.
&lt;a href=javascript:alert(document.domain)>click here&lt;/a>

**Comment by ghost** [comment]
> with middle mouse

Or Ctrl + Click

**Comment by KOLANICH** [comment]
@Thorin-Oakenpants

**Comment by hackademix** [comment]
I could not reproduce (tested on Firefox stable and beta).
As expected, the CSP injected by NoScript causes "Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”)."

- Which browser (version) are you testing on?
- Are you in the default configuration?
- Are you using additional extensions and does the problem go away if you disable them?

Thanks!

**Comment by ghost** [comment]
I'm on windows, it's an TOR Browser 8.5.5.
Can you try if it works with local files or maybe these steps will work?

1. Visit a mock server https://ewfewf.free.beeceptor.com with the code
2. Mark it untrusted, page reloads
3. Clicking with left mouse does nothing
4. Ctrl + Click or Mouse Wheel shows alert in new tab.

**Comment by ghost** [comment]
> Are you using additional extensions and does the problem go away if you disable them?

No I uninstalled all the addons and it still works.
I had problems reproducing it in a data:text/html url tho'.

**Comment by ghost** [comment]
Just verified that this also works with uMatrix.
I've first seen this 8M ago https://news.ycombinator.com/item?id=19129407
Hard to believe I am the first to see this if is isn't just me...

**Comment by hackademix** [comment]
Verified on Tor Browser 8.5.5. Luckily this seems a CSP bug in Firefox ESR 60 that's fixed in current 68 (and therefore in Tor Browser 9), just released this week and obsoleting the older version. Closing therefore, thank you for your report.
