### ISSUE TITLE
ns.canScript might still be undefined when the beforeScriptExecute event handler runs the first time

### ISSUE THREAD

**Issue by anbuc** [hackademix/noscript#107]
Browser: Firefox 70.0 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0)
NoScript: 11.0.4

After noscript updated today Youtube stopped working. No script loaded at all.
I discovered that when I deactivated BlockTube, it worked again. But BlockTube had no update recently, so something in noscript changed that triggered the issue

After some debugging I discovered that a new event listener was added [in staticNS.js#L42](https://github.com/hackademix/noscript/blob/ad5f6b1786ad1dc09b88ed9eef9cd558d726a665/src/content/staticNS.js#L42), where `ns.canScript` is referenced. But the first time stepping into the event handler, it was undefined. It would later be defined [in staticNS.js#L98](https://github.com/hackademix/noscript/blob/ad5f6b1786ad1dc09b88ed9eef9cd558d726a665/src/content/staticNS.js#L98)

I'm not entirely sure that is the exact issue or it works as intended and the other Addon does something it shouldn't do, but from the looks of it, it seems to be vulnerable to a race condition

**Comment by hackademix** [comment]
The code you've seen is meant to prevent scripts from running until the policy has been fetched (i.e. until ns.canScript is not undefined anymore) so yes, it is intentional.
I've installed BlockTube and Youtube still works, and working after re-installing NoScript (just in case the order of installation was important).

Does the issue persist for you after a browser restart?
Can you check the message appearing in the console while the page loads (ctrl+shift+K)?
Thanks!

**Comment by anbuc** [comment]
It works _sometimes_. Opening youtube in a new tabs also helps, reloading alone does not. So the order in which the addons load seems to matter, and seems to be random as well.

Thanks for clarifying it. 

I'll see where I go from here. The more I think about it, the less I think there is anything wrong with the way NoScript behaves here

**Comment by hackademix** [comment]
Please check https://github.com/hackademix/noscript/releases/tag/11.0.5rc2

**Comment by anbuc** [comment]
Still happens. Can't say if less often or not though

```
18:29:59.933 [NoScript] Some script managed to be inserted in the DOM while fetching policy, blocking it.
 <script class="js-mozextension7673d330d…be5e2srcscriptsinjectjs" src="moz-extension://7673d330…2/src/scripts/inject.js">
18:29:59.938 [NoScript] Blocked some scripts on https://www.youtube.com/ even though they are actually permitted by policy.
```
