### ISSUE TITLE
After today's noscript  update, violentmonkey scripts and dark reader extension only sometimes works (race condition?)

### ISSUE THREAD

**Issue by pizzadude** [hackademix/noscript#108]
This seems to be the same issue as https://github.com/hackademix/noscript/issues/107

After today's noscript update, violentmonkey scripts (such as 4chan-x https://github.com/ccd0/4chan-x) and the dark reader extension for Firefox (which is a "recommended addon") only work sometimes. There seems to be a race condition. If it doesn't load the userscript or the CSS isn't modified by Dark Reader, I refresh the page like 5 times and it usually works. But this is annoying.

**Comment by Leloup79** [comment]
I understand the intention explained in #107, but still the change in staticNS.js as in 11.0.4 seems to break execution of Violentmonkey scripts.
I have a VM script running over an internal (corporate) site. Execution is prevented. Works smoothly with downgrade to 11.0.3.
Would be sweet to have this investigated/fixed.

FF 70.0 Violentmonkey 2.11.2

**Comment by Leloup79** [comment]
Found this...
https://support.mozilla.org/en-US/kb/some-pages-or-page-elements-fail-load-after-updating
Not sure if related...

**Comment by hackademix** [comment]
Please check [11.0.5rc2](https://github.com/hackademix/noscript/releases/tag/11.0.5rc2), thanks.

**Comment by pizzadude** [comment]
After testing for a bit, it seems to work fine now. Thanks. :)

**Comment by TheDreka** [comment]
Still having a similar issue with GM/VM userscripts on 11.0.5rc2. Messaging in console did change on the dev version, though:

[NoScript] Blocked some scripts on https://www.youtube.com/watch?v=bJY08LFLCx8 even though they are actually permitted by policy.

**Comment by SenpaiSharp** [comment]
> [NoScript] Blocked some scripts on https://www.youtube.com/watch?v=bJY08LFLCx8 even though they are actually permitted by policy.

Not sure how related it is to the specific topic but in 11.0.4 and 11.0.5rc2 while using Youtube in no_polymer modes, things like the search results popup and the theater mode button on the video control are not working.

**Comment by Leloup79** [comment]
Looks very promising, thanks for the effort!
However, it seems as if still execution of VM scripts _might_ be affected...
1) Open site using VM script 1st try --> everything fine
2) Repeat (in new tab) --> VM script executed partially
3) Repeat (in new tab) --> everything fine again

**Comment by TheDreka** [comment]
For my part, my issues were finally resolved by changes in 11.0.5rc3. Much appreciated.

**Comment by pizzadude** [comment]
@Leloup79 @TheDreka @SenpaiSharp Should I close this, then?

**Comment by SenpaiSharp** [comment]
Latest RC fixes seems to have fixed the Youtube issues, so for my part, yes.

**Comment by Leloup79** [comment]
I have now installed 11.0.6. Looks good to me.
Previously I had an issue as my VM script had a reload mechanism that failed (while the script ran fine on initial load of the page).

Thanks so much for the fix!
And thanks for making this addon happen! Would never want to go without it :-)

**Comment by pizzadude** [comment]
@hackademix This is an issue again with the latest NoScript version.

**Comment by Leloup79** [comment]
Thanks for letting us know. I'll look out if it happens to me.
If it gets fixed just half as fast as last time, there's no need to brace.

@pizzadude I just love your username ;-)

**Comment by pizzadude** [comment]
This setting in Violentmonkey seems to fix it, although further testing is required.
![image](https://user-images.githubusercontent.com/1454420/89692793-acb16b00-d8da-11ea-944c-1f551cd1ff78.png)

**Comment by hackademix** [comment]
Please check [11.0.37rc1](https://github.com/hackademix/noscript/releases/tag/11.0.37rc1), thanks.

**Comment by pizzadude** [comment]
Confirmed fixed. Thanks. :)
