### ISSUE TITLE
Google maps not working

### ISSUE THREAD

**Issue by meelten** [hackademix/noscript#117]
Firefox 70.0.1
NoScript 11.0.8

Google maps doesn't load overlay, showing only bare map without any UI elements at all. Everything on site is "trusted" (which is only google.com and gstatic). With Noscript disabled everything works.

**Comment by hackademix** [comment]
Cannot reproduce.
Could you check whether the problem persists in a clean profile with just NoScript installed (default configuration)?
If it does not, could you please
1. Try to disable your extensions one by one, and check whether the problem goes away (it might be a conflict)
2. Send me your NoScript Options>Export configuration file
?
Thanks!

**Comment by meelten** [comment]
> Cannot reproduce.
> Could you check whether the problem persists in a clean profile with just NoScript installed (default configuration)?
> If it does not, could you please
> 
>     1. Try to disable your extensions one by one, and check whether the problem goes away (it might be a conflict)
> 
>     2. Send me your NoScript Options>Export configuration file
>        ?
>        Thanks!

Sorry for confusion, it's my fault after all. I forgot that I had disabled webgl in my "Trusted" profile. With enabled webgl everything works.
