### ISSUE TITLE
Blocking javascript for file:// while saying that the permissions cannot be configured

### ISSUE THREAD

**Issue by bjorn3** [hackademix/noscript#118]
The noscript dialog says: "This is a privileged page, whose permissions cannot be configured." While at the same time the console says "[NoScript] Some script managed to be inserted in the DOM while fetching policy, blocking it."

Using the "Disable restrictions for this tab" does work though.

**Comment by bjorn3** [comment]
By the way, this is a flamegraph svg.

**Comment by hackademix** [comment]
Isn't this https://forums.informaction.com/viewtopic.php?f=7&t=25807&p=101327#p101327 (fixed in 10.0.10rc1)?

**Comment by bjorn3** [comment]
I think so.
