### ISSUE TITLE
Settings export button broken on the Vivaldi browser (Linux).

### ISSUE THREAD

**Issue by tnilzon** [hackademix/noscript#124]
NoScript has an issue on the Vivaldi browser.

It is not possible to export the NoScript options. Clicking on the Export-button in NoScript/Options opens the browser download dialog, but when selecting Save (or Save As) noting happens, noting is exported.

Operating system: Linux Manjaro Gnome 3.34.2
Vivaldi version: 2.10.1745.21 (Stable channel) (64-bit)
NoScript version: 11.0.9

![Screenshot from 2019-12-23 11-14-59](https://user-images.githubusercontent.com/6920015/71352612-11e86400-2577-11ea-88c4-595344429682.png)

**Comment by hackademix** [comment]
Fixed in https://github.com/hackademix/noscript/releases/tag/11.0.12rc2

**Comment by tnilzon** [comment]
Great, thanks!
