### ISSUE TITLE
Add an option to trust all websites in LAN

### ISSUE THREAD

**Issue by tukusejssirs** [hackademix/noscript#130]
I’d like to have an option to trust all websites in LAN, or maybe even a subset of the LAN.

For example:
- trust all `192.168.1.*`;
- don’t trust all `192.168.0.*`;
- trust all `10.*.*.*`.

**Comment by KOLANICH** [comment]
👎  you shouldn't blindly trust any websites, including ones in LAN. You connect untrusted devices to LAN such as smartphones. Your router can also be compromised.
