### ISSUE TITLE
NoScript blocks DuckDuckGo Search Engine on Firefox

### ISSUE THREAD

**Issue by qwrtln** [hackademix/noscript#138]
While having NoScript enabled and using DuckDuckGo as a default search engine in Firefox, duckduckgo.com sites won't open. It also won't open if I type duckduckgo.com in the address bar manually. Clicking on a link works fine though but it's a pain. Tried clearing the browser cache, history, nothing helps. The only workaround is either to disable NoScript or default to another search engine altogether. What can be done about this?

**Comment by tomeon** [comment]
Chiming in to say that I am affected by this as well.  Problem began about a week ago.  As @qwrtln said, switching to a different default search engine works around the issue -- however, even with a different default search engine, I cannot use the address bar to go directly to "[https://duckduckgo.com](https://duckduckgo.com)".

Copied from the "About Mozilla Firefox" page:

```
77.0.1(64)
Mozilla Firefox for Arch Linux
archlinux - 1.0
```

Happy to gather other information if it would be helpful in diagnosing this issue.

Thanks in advance!

**Comment by tomeon** [comment]
Ah hah - clicking "Clear XSS Choices" in the "Advanced" tab of the NoScript settings page appears to have fixed the issue.

**Comment by octimis** [comment]
"Clear XSS Choices' no longer appears
https://i.imgur.com/IoEjn81.png

**Comment by hackademix** [comment]
> "Clear XSS Choices' no longer appears https://i.imgur.com/IoEjn81.png

That most likely mean you've recorded no exception (choice) of yours yet (or you already cleared them all).
