### ISSUE TITLE
[FF Quantum] Issue with local devices

### ISSUE THREAD

**Issue by Symbai** [hackademix/noscript#14]
Accessing devices in local area network via browser doesn't work with latest NoScript addon as it blocks JS and I cannot get it to allow it. In my case its my NAS which I access in browser via the device name -> https://diskstation:5001 and this is how the setting menu looks like on the page I'm trying to access:

![grafik](https://user-images.githubusercontent.com/14368203/44519779-95f9b580-a6bd-11e8-9ae9-ba666938652e.png)

As you can see I've trusted the site (which isn't named there for whatever reason). But JS is still blocked after refreshing the site.

**Comment by hackademix** [comment]
Are you sure you're using latest NoScript (10.1.8.17)? I believe this known issue has been fixed [here](https://github.com/hackademix/noscript/pull/13). Please confirm, thanks.

**Comment by Symbai** [comment]
I've manually checked for updates and it updated NoScripts. You were right, the issue seems to be fixed.
