### ISSUE TITLE
Req: Dark mode

### ISSUE THREAD

**Issue by Jonta** [hackademix/noscript#142]
I use the dropdown to enable scripts the most, I assume other users do too, so if incremental, I suggest starting there, before moving on to the settings-screen and the high contrast mode

**Comment by demostanis** [comment]
Any update on this?

**Comment by hackademix** [comment]
Are there any other popular/recommended extensions around implementing dark-mode, as a template to follow? (just checked uBlock and HTTPS Everywhere, they don't).

**Comment by demostanis** [comment]
uBlock supports dark mode in dev builds. CanvasBlocker supports a dark mode too.

**Comment by demostanis** [comment]
In `lib/theme.js`, CB uses
```
if (window.matchMedia("(prefers-color-scheme: dark)").matches){
     theme = "dark";
}
```
to know whether it should be dark or not.

**Comment by anmutech** [comment]
Tab Session Manager is another good example for a well implemented dark mode of an extension.

**Comment by demostanis** [comment]
Any update on this?

**Comment by Felipe9999** [comment]
This should be closed because dark mode has been added with the new UI changes
![image](https://user-images.githubusercontent.com/70220216/160213895-64c11f1a-8339-4cd0-9415-109852362918.png)

**Comment by ynakao** [comment]
Yes, but buttons in the top row are still light when `High contrast` is checked.

![noscript_dark](https://user-images.githubusercontent.com/6405335/160217624-01b8bffb-3e32-4d47-ae66-2460b8dba69f.jpg)

**Comment by Felipe9999** [comment]
> Yes, but buttons in the top row are still light when `High contrast` is checked.
> 
> ![noscript_dark](https://user-images.githubusercontent.com/6405335/160217624-01b8bffb-3e32-4d47-ae66-2460b8dba69f.jpg)

I think that's somehow related with high contrast being - as its name implies - high contrast. Still, would be a nice UI change request for those boxes to be dark as well.
On my comment, however, I was referring to the normal dark mode, not high contrast mode with dark theme

**Comment by Croydon** [comment]
This seems to be done for both default dark mode and dark mode + high contrast. Issue can be closed.

**Comment by hackademix** [comment]
> This seems to be done for both default dark mode and dark mode + high contrast. Issue can be closed.

Correct, thank you.
