### ISSUE TITLE
Allow button is greyed out and inactive - FAQ solution unavailable

### ISSUE THREAD

**Issue by moustachio-belvedere** [hackademix/noscript#144]
As of this evening, I am not able to allow scripts on many sites. I did not change any settings before this change in behaviour occurred. I found this FAQ on the website:

https://noscript.net/faq#qa3_22

But the option to change HTTPS behaviour does not exist as far as I can see. In the advanced tab options I only have two choices: Sanitize cross-site suspicious requests, Debug.

I am using Firefox 77 on Windows 7, Noscript version 11.0.29.

Happy to provide more details on request, I don't know what other info might be useful.

**Comment by hackademix** [comment]
If you're experiencing this in a Private Browsing Mode (AKA Incognito) window, that's working as intended (not to leave unintended permanent traces of your navigation on disk, per PBM "contract"):

v 11.0.27rc6
============================================================
x Don't enforce Incognito UI restrictions if the "Override
Tor Browser Security Level preset" option is checked

v 11.0.27rc5
============================================================
x Enter key closes the popup also while editing the CUSTOM
preset
**x Incognito-aware permissions persistence and UI
(https://trac.torproject.org/projects/tor/ticket/29957)**
x Removed inline preset options relics


More discussion here: https://forums.informaction.com/viewtopic.php?p=102190#p102190

**Comment by moustachio-belvedere** [comment]
Thanks for explaining it so quickly. I cannot currently figure out how to open tabs in non-private mode in the firefox settings so for now I will try and implement the hack suggested in your discussion linked, and I will keep an eye out for possible advanced option in 11.0.30.

**Comment by jtotht** [comment]
@hackademix I checked this in a private browsing window. While it works as intended, it’s quite unintuitive—the buttons are greyed out, but nothing explains why. There should be a tooltip, a popup after clicking, or something like this that lets the user know that these buttons are disabled because of PBM. (There’s something about private browsing in FAQ entry 3.26, but it looks like it was written NoScript “Classic”.)
