### ISSUE TITLE
Popup in options page doesn't work properly

### ISSUE THREAD

**Issue by Diklabyte** [hackademix/noscript#15]
__Steps to reproduce__:
Open the NoScript Options page and click the NoScript icon.

__Current behavior__:
The Popup show unusually a small window, after leave the pop up, a extended NoScript extension window appears.

__Expected behavior__:
The popup shows the privileged page warning message, and no extended window will appear.

NoScript version: *10.1.8.22*

**Comment by hackademix** [comment]
Fixed in 10.1.9, thanks.
