### ISSUE TITLE
Local media files unviewable

### ISSUE THREAD

**Issue by Square789** [hackademix/noscript#153]
Win7 64bit; Firefox 80.0.1; NoScript 11.0.42

After viewing the tab for a variable amount of time, around 1 to 10 seconds, the file is displayed as a single, horribly malformed Unicode string.
This issue does not occur when toggling NoScript off in the Add-on management section.

## Opening a gif with NoScript disabled (also occurs for png and mp3 files):
![grafik0](https://user-images.githubusercontent.com/46634729/92418172-6879ea80-f166-11ea-9b8d-13d74e54f0cb.png)
## Activating NoScript and opening the same GIF in a new tab:
![grafik1](https://user-images.githubusercontent.com/46634729/92418185-79c2f700-f166-11ea-8762-e174c6033f5f.png)
## Switching back to the first tab, which is now garbled as well:
![grafik2](https://user-images.githubusercontent.com/46634729/92418249-d4f4e980-f166-11ea-9167-f70506f1b6a5.png)

**Comment by hackademix** [comment]
Could you check this? Thanks.
[v 11.0.43rc1](https://noscript.net/getit#devel)
============================================================
x Should fix some race conditions causing corruptions in
non-HTML non-XML documents

**Comment by Square789** [comment]
The latest development download link 404s, but hacking in all commits into the unzipped xpi file and loading it as a temporary add-on has indeed worked and files load as expected again! Guess I'll mark this as closed and thank you a lot!
