### ISSUE TITLE
[tor-browser] Cannot play youtube videos (scripts allowed, media disallowed)

### ISSUE THREAD

**Issue by acatarineu** [hackademix/noscript#154]
This is https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40093 in Tor Browser issue tracker (I'm not sure if the @ma1 account in torproject's gitlab is working, so opening the issue here meanwhile).

This happens on 78+ version of Firefox. An error is displayed (`An error occurred. Please try again later.`) instead of the usual noscript click-to-play placeholder. As mentioned in that issue, I bisected this down to https://hg.mozilla.org/mozilla-central/rev/039e8fd2928d, but I'm not sure how those changes are exactly causing this issue.

**Comment by hackademix** [comment]
It should have been fixed by commit dcb6bda90ba579a32afd0597a58ee1566a5a37f4, included in [latest 11.0.44 RCs](https://noscript.net/getit#devel).
I've requested a Tor Project gitlab account to notify you there two days ago, but it doesn't seem to be granted yet.

**Comment by acatarineu** [comment]
Thanks! Then I think we can close this.
