### ISSUE TITLE
NoScript 11.0.46 breaks TiddlyWiki5 File Backups V0.4.0 on FF 81.0

### ISSUE THREAD

**Issue by pinysuse** [hackademix/noscript#156]
# Issue
[File Backup Utility For TiddlyWiki] is a great FF Add-on to save a single file [TiddlyWiki5].
Since latest version of NoScript 11.0.46 [File Backup Utility For TiddlyWiki] is broken.

# Steps to Reproduce

1. Download fresh `empty.html` from TiddlyWiki5];
1. Move to a sub-folder within the `~/Downloads` tree and rename appropriately
1. Open from within FF via the **_File menu_** via `~/Downloads` path
1. Create a new tiddler with some text in the body
1. Commit the tiddler

# Result

1. The Commit does not trigger an automatic `save` of the wiki html file as it should
1. The new tiddler is saved however the tiddlers body is **empty**
1. The wiki html file is saved as new copy directly in `~/Downloads` folder instead of updating the file which was loaded in a sub-folder of `~/Downloads`
1. A new backup file is correctly created at the intended location (w/ pre change content)

# Expected Result

1.  Commit of a new/modified tiddler should autosave the wiki html file at the correct location
2. Modified tiddlers body content should not get lost

# Debug info

1. Presumably all permissions on `file://` are set
1. During initial loading of the wiki html file The FF Developer Console produces
   - several `Suppressed script` messages
   - another `Suppressing load` message
1. Initiating an explicit `save` of the wiki html file, the FF Console debug output is
   `<empty string> saver-handler: Saving wiki with method save through saver download <empty string> $:/core/modules/utils/logger.js:52:26`
1. Opening a tiddler for modification, the FF Console debug output is
  ```
freezing file:///home/peter/Downloads/tw_dir/tw_save_test_03/save_test_03.html DocumentFreezer.js:81:15
sendSyncMessage suspend #0/1 SyncMessage.js:226:19
Suppressing readystatechange on  
HTMLDocument file:///home/peter/Downloads/tw_dir/tw_save_test_03/save_test_03.html
DocumentFreezer.js:18:13
Unfreezing file:///home/peter/Downloads/tw_dir/tw_save_test_03/save_test_03.html DocumentFreezer.js:97:15
Opened null syncFetchPolicy.js:60:23
sendSyncMessage finalizing SyncMessage.js:239:19
sendSyncMessage resume #0/0 - 127ms SyncMessage.js:235:19
sendSyncMessage finalizing SyncMessage.js:239:19
```

# Notes

- Committing a tiddler, the FF Console debug output is
`<empty string> saver-handler: Saving wiki with method autosave through saver tiddlyfox <empty string> $:/core/modules/utils/logger.js:52:26`
- Explicitly saving wiki, the FF Console debug output is
`<empty string> saver-handler: Saving wiki with method save through saver tiddlyfox <empty string> $:/core/modules/utils/logger.js:52:26
`
- Disabling NoScript in the **_Manage Your Extensions_** page of FF makes _TiddlyWiki5 File Backups_ work as intended
- Setting NoScript option `Disable restrictions globally (dangerous)` does not solve the issue

# Assumption
The inital script suppressions break the details of the **_saver tiddlyfox_** which is still executed somehow

[File Backup Utility For TiddlyWiki]: https://pmario.github.io/file-backups/
[TiddlyWiki5]: https://tiddlywiki.com/#GettingStarted

**Comment by pinysuse** [comment]
# FF Console Debug output during initial load of a wiki html file

(excerpts deemed relevant)

```
Freezing file:///home/peter/Downloads/tw_dir/tw_save_test_03/save_test_03.html DocumentFreezer.js:81:15

Suppressed script #1 
<script data-tiddler-library="yes" data-tiddler-title="$:/library/sjcl.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:75:13
Suppressing beforescriptexecute on  
<script data-tiddler-library="yes" data-tiddler-title="$:/library/sjcl.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:18:13

Suppressed script #2 
<script data-tiddler-title="$:/boot/bootprefix.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:75:13
Suppressing beforescriptexecute on  
<script data-tiddler-title="$:/boot/bootprefix.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:18:13

Suppressed script #3 
<script data-tiddler-title="$:/boot/boot.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:75:13
Suppressing beforescriptexecute on  
<script data-tiddler-title="$:/boot/boot.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:18:13
Suppressing readystatechange on  
HTMLDocument file:///home/peter/Downloads/tw_dir/tw_save_test_03/save_test_03.html
DocumentFreezer.js:18:13

Suppressing load on  
<style data-tiddler-title="$:/boot/boot.css" data-tiddler-type="text/css" type="text/css">
DocumentFreezer.js:18:13
sendSyncMessage finalizing SyncMessage.js:239:19
Unfreezing file:///home/peter/Downloads/tw_dir/tw_save_test_03/save_test_03.html DocumentFreezer.js:97:15
```

**Comment by pinysuse** [comment]
# Notes:
- Disabling NoScript in the **_Manage Your Extensions_** page of FF makes _TiddlyWiki5 File Backups_ work as intended
- Setting NoScript option `Disable restrictions globally (dangerous)` does not solve the issue

**Comment by pmario** [comment]
I could follow the problem down to: DocumentFreezer.js line: 17/18 ... Even if you set the site to be trusted, the plugin runs to line 17, which stops event propagation. So the TW editor doesn't get the keyboard events, which in turn prevents its functionality. 

I did set the configuration to "trust". I did click the "file" indicator so the icon was green. ... Nothing seems to help here.

**Comment by pmario** [comment]
For me the addON also completely messes up github UI, so I needed to remove it.

**Comment by pinysuse** [comment]
Confirmed the findings of  [pmario](https://github.com/pmario): 
- Disable File Backups AddOn
- New tiddlers can be created but no tiddler content is saved
- NoScript appears to break the TiddlyWiki application

**Comment by hackademix** [comment]
Please check [NoScript 11.0.47rc4](https://noscript.net/getit#devel), thanks.

**Comment by pmario** [comment]
I did a short test with FF81 ubuntu 20.04 and it looks good.  I'll test again later today.

**Comment by pinysuse** [comment]
> Please check [NoScript 11.0.47rc4](https://noscript.net/getit#devel), thanks.

Thanks for providing this test release!

New tiddler can be created and their content is preserved in the wiki.
However, the saving mechanism of File Backups is still broken because the saved wiki is still saved directly in the Downloads folder as new file instead of within the specified sub folder (within the Downloads tree) as a new version.

Console debug output (excerpts):

```
Suppressed script #1 
<script data-tiddler-library="yes" data-tiddler-title="$:/library/sjcl.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:75:13
Suppressing beforescriptexecute on  
<script data-tiddler-library="yes" data-tiddler-title="$:/library/sjcl.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:18:13
(...)
Suppressed script #2 
<script data-tiddler-title="$:/boot/bootprefix.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:75:13
Suppressing beforescriptexecute on  
<script data-tiddler-title="$:/boot/bootprefix.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:18:13
(...)
Suppressed script #3 
<script data-tiddler-title="$:/boot/boot.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:75:13
Suppressing beforescriptexecute on  
<script data-tiddler-title="$:/boot/boot.js" data-tiddler-type="application/javascript" type="text/javascript">
DocumentFreezer.js:18:13
Suppressing readystatechange on  
HTMLDocument file:///home/peter/Downloads/tw_dir/tw_save_test_03/save_test_03.html
DocumentFreezer.js:18:13
(...)
Suppressing load on  
<style data-tiddler-title="$:/boot/boot.css" data-tiddler-type="text/css" type="text/css">
DocumentFreezer.js:18:13
(...)
<empty string> saver-handler: Saving wiki with method save through saver download <empty string> $:/core/modules/utils/logger.js:52:26
```

I do believe that `saver tiddlyfox` should be invoked instead of `saver download`.

Cross check: `file://` subdocuments is _trusted_.

**Comment by hackademix** [comment]
Please check [NoScript 11.0.47rc5](https://noscript.net/getit#devel), thanks.

**Comment by pmario** [comment]
>I do believe that saver tiddlyfox should be invoked instead of saver download.

That's right. .. 

Make sure, that you reload the tab, that contains the wiki after you did disable / enable the file-backups plugin!

**Comment by pinysuse** [comment]
> Please check [NoScript 11.0.47rc5](https://noscript.net/getit#devel), thanks.

Works as intended - great!
Thanks [hackademix](https://github.com/hackademix) and [pmario](https://github.com/pmario) for fixing the issue so fast!
