### ISSUE TITLE
Outdated list of scripts (firefox android)

### ISSUE THREAD

**Issue by Mindavi** [hackademix/noscript#161]
I'm using Firefox Nightly 201128 17:02 (Build #2015778315) with NoScript 11.1.5. Android version 10, LineageOS. I have been having this issue for a while now, I've probably updated the browser a couple of times. It does not seem to be tied to one browser version or one NoScript version.

I have been noticing issues where noscript shows outdated / incorrect info on the scripts that are or are not blocked. In that case, it seems like the script count indicator is correct (e.g. it shows 3 blocked scripts). However, when I click on the NoScript icon it only shows one website (in most cases). It appears it's typically my main search engine that's shown. That search engine only shows 1 blocked script.

This happens on different websites, and the only way to resolve this seems to be to restart the browser. However, that doesn't always resolve it either.

If I can help in any way by providing logs or something like that, please let me know.

**Comment by hackademix** [comment]
Please notice that the badge counts scripts grouped by origin, i.e. it's incremented by one for each type of capability triggered by a different origin: if there are 4 scripts all from acme.com, the increment will be just by 1. Is this consistent with what you're observing?

**Comment by Mindavi** [comment]
No, it shows (for example) 4 scripts, and when I then click on it, it shows scripts from a wholly different website (so instead of the website I was looking on, it showed scripts from duckduckgo). When I then reset the browser by force stopping, it shows the scripts that belong to the page again.

So I don't think this is related to a mismatch between hosts and number of scripts.

**Comment by Mindavi** [comment]
I haven't noticed any issues anymore the last few months, so I'm gonna close this. It appears to be resolved for me.

Using NoScript 11.4.6 with firefox (Fennec F-Droid) 101.1.1.

Thanks for the great work, still using this addon with pleasure!
