### ISSUE TITLE
"cascade top document's restriction to subdocuments" - how does it work?

### ISSUE THREAD

**Issue by meelten** [hackademix/noscript#163]
In my understanding enabling this option should prevent 3rd party scripts to have less restrictions than 1st party domain however I'm unable to verify that. Whether this option is enabled or not I can't see any impact. Let's take github as example: when I add "githubassets.com" to whitelist and have "github.com" as default (with everything blocked) then "githubassets.com" is still showed as "trusted" in Noscript pop-up.

Do I understand something wrong here? Maybe it after all works as intended "under the hood" only pop-up is misleading?
In fact I wonder if this option is even implemented because in config txt (when you export settings or view them in Advanced -> Debug) is no line corresponding to this.

**Comment by hackademix** [comment]
This option ensures that the permissions given to a certain subdocument are the intersection between the top document and the page's own. The presets of the subdocument is not changed, though, therefore you won't see any difference in the popup.
You can see what's going on here: https://noscript.net/test/cascade_restrictions/
