### ISSUE TITLE
"media" filter doesn't seem to be working

### ISSUE THREAD

**Issue by thany** [hackademix/noscript#169]
When I untick the "media" filter for the untrusted profile, it'll still happily load images on an untrusted domain.
I've verified if the image is coming from the same domain, and it is.

I've found this issue at [a bit of a naughty site](https://sukebei.iss.one/) but the issue seems to present itself even on google.com if I set that to untrusted. So it's possibly not related to any one site or domain.

OS: Windows 10 20H2
Browser: Firefox 84.0.2
Addon version: 11.1.9

**Comment by hackademix** [comment]
The "media" capability is not meant to affect images. It applies to HTML 5 media elements (<video>, <audio> and <media>), which pose a higher attack surface risk because of possible vulnerabilities in the various decoders that can be engaged.
