### ISSUE TITLE
Please allow noscript elements on script-disabled pages by default

### ISSUE THREAD

**Issue by tappahannock** [hackademix/noscript#175]
Since 11.2.1 NoScript started blocking noscript elements by default on all pages. Until then, those tags provided ability for pages to detect if user has scripts disabled or blocked and could offer alternative, nojs interfaces or redirect to nojs frontends. Because of incomprehensible reason addon changed its behavior recently and now almost all NoScript friendly websites are broken:

NoScript changelog for 11.2.1:
> x Configurable capability to show noscript elements on script-disabled pages

All users who want to repair it have to customize their settings in NoScript and know which box to select. I would argue if every site owner will now change code on their websites and implement some different weird HTML tricks because of NoScript addon users. Those are two examples how it works now:

Bitcoin Explorer Blockstream.info:
`<noscript><meta http-equiv="refresh" content="0; url='?nojs'"></noscript>`

Search engine DuckDuckGo:
`<noscript><meta http-equiv="refresh" content="0;URL=/html?q=github"><link href="/css/noscript.css" rel="stylesheet" type="text/css"><div class="msg msg--noscript"><p class="msg-title--noscript">You are being redirected to the non-JavaScript site.</p>Click <a href="/html/?q=github">here</a> if it doesn't happen automatically.</div></noscript>`

**Comment by KOLANICH** [comment]
They were blocked on purpose: they are usually used in the "modern web" to redirect users from partially working pages to the pages "you must enable JS" and "you must install a supported browser (Google Chrome is mentioned first)".

**Comment by KOLANICH** [comment]
I remember that in XUL/XPCOM-based versions of NoScript there was a feature to ignore only noscripted redirects.

**Comment by hackademix** [comment]
> All users who want to repair it have to customize their settings in NoScript 

The DEFAULT preset does have the [noscript] capability enabled out of the box, and upon updates from previous versions where it didn't exist yet NoScript tries its best to flip it on for any policy which as [script] disabled.

I suppose you've experienced some bug in this upgrade process which left it disabled, but otherwise (at least for new installations) I believe this issue can be closed. Feel free to reopen it if I'm missing something, thanks.
