### ISSUE TITLE
Add the Chrome extension to Edge Chromium store

### ISSUE THREAD

**Issue by Witchilich** [hackademix/noscript#176]
Edge Chromium can use the Chrome extension, but having it in Edge store will help with sync.

**Comment by arixmkii** [comment]
+1 for this as I would guess that at some point (if not already) extensions from external stored might be limited by domain policy on Enterprise versions and these will be the users, which are most common locked to use only preinstalled browser. So, having extension published also in MS store could cover some additional users, besides being more convenient for Edge Chromium browsers.

**Comment by nagachaitanyalokam** [comment]
Microsoft Edge is the second most used browser on the web, making the browsing experience more flexible, offering many more services for users and optimized for Windows devices.

Microsoft Edge supports Chromium extensions, and you can publish your extensions to Microsoft Edge Add-ons website with minimal code changes. Find out more [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension).

If you have any more queries about porting Chrome extension to Microsoft Edge or anything else, you can contact the relevant teams whose links are given [here](https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/contact-extensions-team). 

Let me know if this was helpful. I am happy to help you with more details.

**Comment by arixmkii** [comment]
https://microsoftedge.microsoft.com/addons/detail/noscript/debdhlbmgmkkfjpcglcbjadbhhekgfjh
I believe this one is solved and can be closed.
