### ISSUE TITLE
BitBucket not loading despite disabling NoScript

### ISSUE THREAD

**Issue by Cor73** [hackademix/noscript#179]
Hello,

I recently installed NoScript (and it works great).
My issue so far is that when I go to BitBucket (for example: https://bitbucket.org/mituharu/emacs-mac/overview ), the site does not load (just a blank page).

My setup with NoScript is just the defaults.

My troubleshooting steps so far:

1. I selected all the permissions of this website to 'Trust' ==> reloaded the tab ==> site does not load
2. I selected "Disable restrictions for this tab" ==> reloaded the tab ==> site does not load
3. I even disabled the NoScript addon in Firefox ==> restarted FireFox ==> the site still does not load.

I know this is an issue with NoScript because this site was working prior to installing it (and there were no other confounding factors with my set up i.e. I had not changed anything else apart from installing NoScript).
I have run into a few sites which sometimes breaks like this, just wondering what could be done?

Using latest version of NoScript in Mac OSx with Firefox 87

Kind regards,

**Comment by hackademix** [comment]
https://bitbucket.org/mituharu/emacs-mac/overview works just fine for me with a default NoScript installation, after setting to TRUSTED both bitbucket.com and a cloudfrount.net dependency.

Anyway, if a site doesn't work even after _disabling_ NoScript and reloading, that definitely rules out NoScript as the culprit and you should look into interference from other extensions, browser configuration or external software (AV? proxy?)

Good luck and let me know.

**Comment by KOLANICH** [comment]
I advice everyone not to use BitBucket and migrate to GitHub/GitLab/SourceHut if one can. I feel like BitBucket GUI is slower than competitors' because BB relies on JS too much. It has caused Firefox on my machine crashed more than GH and GL combined (for the period of time I used all 3). I don't use it anymore.

**Comment by Cor73** [comment]
Hi,

Thanks both for your replies

> https://bitbucket.org/mituharu/emacs-mac/overview works just fine for me with a default NoScript installation, after setting to TRUSTED both bitbucket.com and a cloudfrount.net dependency.
> 
> Anyway, if a site doesn't work even after _disabling_ NoScript and reloading, that definitely rules out NoScript as the culprit and you should look into interference from other extensions, browser configuration or external software (AV? proxy?)
> 

In that case, I think it might be an issue with my Firefox config file; I think I might have fiddled around with some of those settings and that might be why certain sites are not loading (it was a few weeks ago that I installed NoScript and my memory isn't the best). 
I'll look into it and let you know if I ever find out what setting caused it.

Warm regards,

**Comment by Cor73** [comment]
So after checking through my Firefox about:config I discovered that for some reason, dom.enable_performance was set to false. After changing it to true, BitBucket now loads without issue.
I have no idea how that setting changed from its default, but it all works now!

Thanks again for your help!
