### ISSUE TITLE
Complete form implementation using Javascript with GET method submission via window.location may result in blank page

### ISSUE THREAD

**Issue by pal1000** [hackademix/noscript#18]
This regressed somewhere between 10.1.8.23 and 10.1.9, but it got overshadowed by #4.

Implementing a basic form using GET method exclusively in JavaScript with no server side workload and using window,location to submit it results in initial blank page. This can be reproduced using a webpage stored locally.

### Steps to reproduce
- Create a HTML file with this content:

````
<html><head><title>NoScript redirect handling bug</title>
</head><body>
<script>

function $_GET(key, default_)
{
  if (default_==null) default_="";
  key = key.replace(/[\[]/,"\\\[").replace(/[\]]/,"\\\]");
  var regex = new RegExp("[\\?&]"+key+"=([^&#]*)");
  var qs = regex.exec(window.location.href);
  if(qs == null) qs=default_;
  else qs=qs[1];
  return qs;
}

var form="<input type='button' value='Submit' onclick='submit()'><br>";

if ($_GET('test')=='') document.write(form);

function submit(){
var submitURL=window.location.protocol + '//' + window.location.hostname + window.location.pathname+'?test=test'
window.location=submitURL;
window.location;
}

function play (){
document.write(decodeURIComponent($_GET('test')));
}

if (!$_GET('test')=='') play();
</script>

</body></html>
````
- Open a fresh Firefox session with all web cache cleared;
- Open the webpage created previously. Do not open Firefox with that webpage directly. You need to have Firefox open before attempting to open that webpage, otherwise you won't reproduce this reliably.

### Temporary cure
- Giving focus to address bar and hitting enter allows the page to render displaying what should have been rendered in the first place. The correct behavior is cached by Firefox so you won't be able to reproduce again until the cache is cleared.

**Comment by hackademix** [comment]
This might have been accidentally fixed by [10.1.9.2rc1](https://github.com/hackademix/noscript/releases/tag/10.1.9.2rc1). Please confirm, thanks.

**Comment by pal1000** [comment]
Yes, it's fixed, in a very neat way, I'd say. I didn't expect to get full file protocol support like that.  That's a really comprehensive fix.

However this introduced small confusion in the UI. I'll open a new issue with details about that (#20).

**Comment by pal1000** [comment]
This is back in 10.1.9.2rc2 unfortunately.
