### ISSUE TITLE
SSO login via b2clogin.com fails w/ NoScript

### ISSUE THREAD

**Issue by pinysuse** [hackademix/noscript#181]
NoScript leads to SSO error while login via b2clogin.com.
Enabling b2clogin.com does not help because b2clogin.com tries to pull scripts from windows.net which is not visible to the user.

b2clogin seems to be a Microsoft SSO service which does not provide a direct web page.

This case can be reproduced via the website https://www.theiet.org by activating the {Login}-button on the top right also w/o an account: The Login page will never be reached.
Deactivating NoScript globally reveals the access to windows.net. Enabling it now (temporarily) solves the issue and allow login even w/ NoScript re-enabled.

NoScript 11.2.5rc1
FF 87.0 (64bit)
Linux 5.3.18-lp152.66-default x86_64
openSUSE Leap 15.2
Qt 5.12.7
KDE 5.71.0
Plasma 5.18.6

**Comment by hackademix** [comment]
I've tried to follow your steps to reproduce:

1. I've first set theiet.org to TRUSTED, then used the Login button.
2. I was about to press the [Login with SSO] button on the next page, when I've been automatically redirected to a [a b2clogin.com page](https://ietsso.b2clogin.com/ietsso.onmicrosoft.com/B2C_1A_RPNonMemberSignUpSignInV1.0/oauth2/v2.0/authorize?client_id=f6380d8c-fbe7-472e-959f-98fedbc112ba&response_type=code%20id_token&redirect_uri=https%3A%2F%2Fwww2.theiet.org%2Findex.cfm&state=%7B%22client_id%22%3A%22f6380d8c-fbe7-472e-959f-98fedbc112ba%22%2C%22network%22%3A%22adB2CSignInSignUp%22%2C%22display%22%3A%22page%22%2C%22callback%22%3A%22_hellojs_94rxqq5r%22%2C%22state%22%3A%22%22%2C%22redirect_uri%22%3A%22https%3A%2F%2Fwww2.theiet.org%2Findex.cfm%22%2C%22scope%22%3A%22openid%2Cprofile%2Coffline_access%2Chttps%253A%252F%252Fietsso.b2clogin.com%252Ftasks%252Fread%2520https%253A%252F%252Fietsso.b2clogin.com%252Ftasks%252Fwrite%22%2C%22page_uri%22%3A%22https%3A%2F%2Fwww2.theiet.org%2Flogin%2Findex.cfm%2F%3ForiginUrl%3Dhttps%3A%2F%2Fwww.theiet.org%2F%22%2C%22oauth%22%3A%7B%22version%22%3A2%2C%22auth%22%3A%22https%3A%2F%2Fietsso.b2clogin.com%2Fietsso.onmicrosoft.com%2FB2C_1A_RPNonMemberSignUpSignInV1.0%2Foauth2%2Fv2.0%2Fauthorize%22%2C%22grant%22%3A%22https%3A%2F%2Fietsso.b2clogin.com%2Fietsso.onmicrosoft.com%2FB2C_1A_RPNonMemberSignUpSignInV1.0%2Foauth2%2Fv2.0%2Ftoken%22%7D%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server.herokuapp.com%2Fproxy%22%7D&scope=openid%20profile%20offline_access%20https%3A%2F%2Fietsso.b2clogin.com%2Ftasks%2Fread%20https%3A%2%2Fietsso.b2clogin.com%2Ftasks%2Fwrite) saying I needed to enable JavaScript
3. So I set b2clogin.com as well to TRUSTED, and I automatically landed on [b2clogin.com login page](https://ietsso.b2clogin.com/ietsso.onmicrosoft.com/B2C_1A_RPNonMemberSignUpSignInV1.0/oauth2/v2.0/authorize?client_id=f6380d8c-fbe7-472e-959f-98fedbc112ba&response_type=code%20id_token&redirect_uri=https%3A%2F%2Fwww2.theiet.org%2Findex.cfm&state=%7B%22client_id%22%3A%22f6380d8c-fbe7-472e-959f-98fedbc112ba%22%2C%22network%22%3A%22adB2CSignInSignUp%22%2C%22display%22%3A%22page%22%2C%22callback%22%3A%22_hellojs_94rxqq5r%22%2C%22state%22%3A%22%22%2C%22redirect_uri%22%3A%22https%3A%2F%2Fwww2.theiet.org%2Findex.cfm%22%2C%22scope%22%3A%22openid%2Cprofile%2Coffline_access%2Chttps%253A%252F%252Fietsso.b2clogin.com%252Ftasks%252Fread%2520https%253A%252F%252Fietsso.b2clogin.com%252Ftasks%252Fwrite%22%2C%22page_uri%22%3A%22https%3A%2F%2Fwww2.theiet.org%2Flogin%2Findex.cfm%2F%3ForiginUrl%3Dhttps%3A%2F%2Fwww.theiet.org%2F%22%2C%22oauth%22%3A%7B%22version%22%3A2%2C%22auth%22%3A%22https%3A%2F%2Fietsso.b2clogin.com%2Fietsso.onmicrosoft.com%2FB2C_1A_RPNonMemberSignUpSignInV1.0%2Foauth2%2Fv2.0%2Fauthorize%22%2C%22grant%22%3A%22https%3A%2F%2Fietsso.b2clogin.com%2Fietsso.onmicrosoft.com%2FB2C_1A_RPNonMemberSignUpSignInV1.0%2Foauth2%2Fv2.0%2Ftoken%22%7D%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server.herokuapp.com%2Fproxy%22%7D&scope=openid%20profile%20offline_access%20https%3A%2F%2Fietsso.b2clogin.com%2Ftasks%2Fread%20https%3A%2F%2Fietsso.b2clogin.com%2Ftasks%2Fwrite).
4. Not sure what was needed afterwards to successfully login (I don't have an account there), but sure enough windows.net was among the sites shown in NoScript menu ready to be set to TRUSTED if necessary.

**Comment by pinysuse** [comment]
I did (once again) several tests - details below - all to no avail.
Finally I created a new fresh user, installed NoScript extension to FF and followed your steps.
So I ended up on the desired login page and I also suddenly saw the option to enable `windows.net`.

> **_Success!_**

So something seems to be hidden in my FF profile which I am not able to identify and which somehow interacts w/ NoScript.

Thanks for your support!

--- Fail story below this line ---

I deleted all cookies for `*iet*` (incl. one for b2clogin.com, none for windows.net) to get a clean start and followed exactly your steps.
Steps 1...3 - same procedure besides not landing on a specific `b2clogin.com login page` but get rerouted to theiet.org with a strange error message (?) in the URL:

```
https://www2.theiet.org/index.cfm#error=server_error&error_description=AADB2C90047%3a+The+resource+%27https%3a%2f%2fietpb2cstorage.blob.core.windows.net%2fietpb2ctemplates%2fietsso_signuporsignin.html%27+contains+script+errors+preventing+it+from+being+loaded.%0d%0aCorrelation+ID%3a+cd8b67cc-d8a3-463d-ac4e-88ba90903462%0d%0aTimestamp%3a+2021-04-10+10%3a16%3a01Z%0d%0a&state=%7b%22client_id%22%3a%22f6380d8c-fbe7-472e-959f-98fedbc112ba%22%2c%22network%22%3a%22adB2CSignInSignUp%22%2c%22display%22%3a%22page%22%2c%22callback%22%3a%22_hellojs_52yvyiq2%22%2c%22state%22%3a%22%22%2c%22redirect_uri%22%3a%22https%3a%2f%2fwww2.theiet.org%2findex.cfm%22%2c%22scope%22%3a%22openid%2cprofile%2coffline_access%2chttps%253A%252F%252Fietsso.b2clogin.com%252Ftasks%252Fread%2520https%253A%252F%252Fietsso.b2clogin.com%252Ftasks%252Fwrite%22%2c%22page_uri%22%3a%22https%3a%2f%2fwww2.theiet.org%2flogin%2findex.cfm%2f%3foriginUrl%3dhttps%3a%2f%2fwww.theiet.org%2f%22%2c%22oauth%22%3a%7b%22version%22%3a2%2c%22auth%22%3a%22https%3a%2f%2fietsso.b2clogin.com%2fietsso.onmicrosoft.com%2fB2C_1A_RPNonMemberSignUpSignInV1.0%2foauth2%2fv2.0%2fauthorize%22%2c%22grant%22%3a%22https%3a%2f%2fietsso.b2clogin.com%2fietsso.onmicrosoft.com%2fB2C_1A_RPNonMemberSignUpSignInV1.0%2foauth2%2fv2.0%2ftoken%22%7d%2c%22oauth_proxy%22%3a%22https%3a%2f%2fauth-server.herokuapp.com%2fproxy%22%7d
```

The user gets displayed a text like

> The IET
> 
> Please visit the updated [IET website](https://www.theiet.org/)

which is the entry into an endless loop.
The real target page is one with possibility to enter user credentials.

Next test: Delete all cookies again and directly try above [b2clogin.com login page](https://ietsso.b2clogin.com/ietsso.onmicrosoft.com/B2C_1A_RPNonMemberSignUpSignInV1.0/oauth2/v2.0/authorize?client_id=f6380d8c-fbe7-472e-959f-98fedbc112ba&response_type=code%20id_token&redirect_uri=https%3A%2F%2Fwww2.theiet.org%2Findex.cfm&state=%7B%22client_id%22%3A%22f6380d8c-fbe7-472e-959f-98fedbc112ba%22%2C%22network%22%3A%22adB2CSignInSignUp%22%2C%22display%22%3A%22page%22%2C%22callback%22%3A%22_hellojs_94rxqq5r%22%2C%22state%22%3A%22%22%2C%22redirect_uri%22%3A%22https%3A%2F%2Fwww2.theiet.org%2Findex.cfm%22%2C%22scope%22%3A%22openid%2Cprofile%2Coffline_access%2Chttps%253A%252F%252Fietsso.b2clogin.com%252Ftasks%252Fread%2520https%253A%252F%252Fietsso.b2clogin.com%252Ftasks%252Fwrite%22%2C%22page_uri%22%3A%22https%3A%2F%2Fwww2.theiet.org%2Flogin%2Findex.cfm%2F%3ForiginUrl%3Dhttps%3A%2F%2Fwww.theiet.org%2F%22%2C%22oauth%22%3A%7B%22version%22%3A2%2C%22auth%22%3A%22https%3A%2F%2Fietsso.b2clogin.com%2Fietsso.onmicrosoft.com%2FB2C_1A_RPNonMemberSignUpSignInV1.0%2Foauth2%2Fv2.0%2Fauthorize%22%2C%22grant%22%3A%22https%3A%2F%2Fietsso.b2clogin.com%2Fietsso.onmicrosoft.com%2FB2C_1A_RPNonMemberSignUpSignInV1.0%2Foauth2%2Fv2.0%2Ftoken%22%7D%2C%22oauth_proxy%22%3A%22https%3A%2F%2Fauth-server.herokuapp.com%2Fproxy%22%7D&scope=openid%20profile%20offline_access%20https%3A%2F%2Fietsso.b2clogin.com%2Ftasks%2Fread%20https%3A%2F%2Fietsso.b2clogin.com%2Ftasks%2Fwrite).

No avail, similar result
```
https://www2.theiet.org/index.cfm#error=server_error&error_description=AADB2C90047%3a+The+resource+%27https%3a%2f%2fietpb2cstorage.blob.core.windows.net%2fietpb2ctemplates%2fietsso_signuporsignin.html%27+contains+script+errors+preventing+it+from+being+loaded.%0d%0aCorrelation+ID%3a+4bf934ca-3bdd-4d16-bae5-3cd378d919cb%0d%0aTimestamp%3a+2021-04-10+10%3a22%3a28Z%0d%0a&state=%7b%22client_id%22%3a%22f6380d8c-fbe7-472e-959f-98fedbc112ba%22%2c%22network%22%3a%22adB2CSignInSignUp%22%2c%22display%22%3a%22page%22%2c%22callback%22%3a%22_hellojs_94rxqq5r%22%2c%22state%22%3a%22%22%2c%22redirect_uri%22%3a%22https%3a%2f%2fwww2.theiet.org%2findex.cfm%22%2c%22scope%22%3a%22openid%2cprofile%2coffline_access%2chttps%253A%252F%252Fietsso.b2clogin.com%252Ftasks%252Fread%2520https%253A%252F%252Fietsso.b2clogin.com%252Ftasks%252Fwrite%22%2c%22page_uri%22%3a%22https%3a%2f%2fwww2.theiet.org%2flogin%2findex.cfm%2f%3foriginUrl%3dhttps%3a%2f%2fwww.theiet.org%2f%22%2c%22oauth%22%3a%7b%22version%22%3a2%2c%22auth%22%3a%22https%3a%2f%2fietsso.b2clogin.com%2fietsso.onmicrosoft.com%2fB2C_1A_RPNonMemberSignUpSignInV1.0%2foauth2%2fv2.0%2fauthorize%22%2c%22grant%22%3a%22https%3a%2f%2fietsso.b2clogin.com%2fietsso.onmicrosoft.com%2fB2C_1A_RPNonMemberSignUpSignInV1.0%2foauth2%2fv2.0%2ftoken%22%7d%2c%22oauth_proxy%22%3a%22https%3a%2f%2fauth-server.herokuapp.com%2fproxy%22%7d
```

Repeating the test w/ all other extensions disabled - same result.

Actually, I never see `windows.net` appear within the NoScript settings menu as long as NoScript is enabled!

> so I resorted to check w/ a fresh user account - see to of this post.
