### ISSUE TITLE
WebGL hook in 11.2.4

### ISSUE THREAD

**Issue by roman567e45** [hackademix/noscript#187]
WebGL hook (webglHook.js) was rewritten from:
`if (type && type.toLowerCase().includes("webgl")) {` (v11.2.3)
to
`if (/^webgl2?$/.test(type)) {` (v11.2.4)
but it doesn't handle all contexts, like 'experimental-webgl'

see: https://browserleaks.com/webgl
WebGL (v1) doesn't work as click-to-play for now.

All possible contexts are: webgl2, experimental-webgl2, webgl, experimental-webgl, moz-webgl.

**Comment by hackademix** [comment]
Thank you for catching that, should be fixed in [11.2.5rc5](https://secure.informaction.com/download/betas/noscript-11.2.5rc5.xpi).
Aiming to submit 11.2.5 stable on AMO tomorrow.
