### ISSUE TITLE
Could not play music on Deezer even with restrictions turned off globally

### ISSUE THREAD

**Issue by l0drex** [hackademix/noscript#189]
I currently have an issue with playing music on Deezer. Even after turning off all restrictions globally I was not able to play music. The only thing that helped was disabling noscript from the Firefox Add-ons page.

This is weird because it worked perfectly fine before with only necessary scripts enabled. I expected that turning off all restrictions globally should have the same effect as disabling this add-on from the Firefox add-ons page

**noscript Version**: 11.2.6
**Browser**: Firefox v88.0 64 bit
**OS**: Manjaro Linux with KDE Plasma

**Comment by hackademix** [comment]
Should be fixed in [11.2.7rc1](https://noscript.net/getit#devel), thanks.
