### ISSUE TITLE
Cannot use firefox as a media player for local files

### ISSUE THREAD

**Issue by pal1000** [hackademix/noscript#19]
This is a regression but I don't know since when. 

### Prerequisite
- a HTML5 compatible media file with audio, video or both tracks - it doesn't matter. It has to be on local computer and served over file protocol.

### Steps to reproduce
- Just try opening a locally stored media file in Firefox and see what happens:
![media-null](https://user-images.githubusercontent.com/1138235/44907243-f1601f00-ad1f-11e8-89c0-12933ab84c3e.png)
Allowing `<MEDIA>@null` won't help.

**Comment by hackademix** [comment]
This should be fixed in [10.1.9.2rc1](https://github.com/hackademix/noscript/releases/tag/10.1.9.2rc1). Please confirm, thanks.
