### ISSUE TITLE
Unnessessary logging in devtools

### ISSUE THREAD

**Issue by solntcev** [hackademix/noscript#191]
https://github.com/hackademix/noscript/blob/dfcd35a0e21e8725bedf46b2e29102fa134984b4/src/bg/RequestGuard.js#L630

on each page load 2 lines are logged

```
domPolicy loading 1620739292407:0.9296232813574                420c3638-21b9-42e3-a327-4f7b2907340b:4:15
DocStartInjection loading Object { __DocStartInjection__: {…} }        9e2a7d28-1a3b-4215-9177-a49b5ef7d0f3:1:9
```

debug is disabled in NoScript settings.
NoScript version 11.2.7

**Comment by hackademix** [comment]
Fixed in 11.2.8 (current stable).
