### ISSUE TITLE
Regression: Load/Reload issues since version 11.2.4

### ISSUE THREAD

**Issue by ib** [hackademix/noscript#195]
Does checking "cap_unchecked_css" turn off the CSS checks completely? Some web pages (such as gmx.de) seem to render visibly slower and you can sometimes see the redirection to subsequent pages for a very short time which wasn't the case before this capability.

**Comment by hackademix** [comment]
Yes, it turns it off completely. What you're observing must be something else.

**Comment by ib** [comment]
Starting from version 11.2.4, the observed and reported issues occur. I compared versions 11.2.3 and 11.2.4.

I have recorded single frames of the login process on gmx.de to illustrate the issue.

As you can see, in version 11.2.3 there is a direct redirect from bap.navigator.gmx.net to 3c-bap.gmx.net.

Starting from version 11.2.4 one gets "stuck" for a short time in bap.navigator.gmx.net and 3c-bap.gmx.net (cookie warning). As a result, sometimes the last frame (link to the mailbox with reduced functionality) does not appear and thus the login does not complete and access to the e-mail is not possible.

(Cookies, except for third-party cookies, are allowed and gmx.* and all other pages have the default profile, allowing only media, frame, font, noscript.)

[11.2.3.zip](https://github.com/hackademix/noscript/files/6532190/11.2.3.zip)
[11.2.4.zip](https://github.com/hackademix/noscript/files/6532191/11.2.4.zip)

**Comment by hackademix** [comment]
1. Does the same problem persist in  NoScript 11.2.8?
2. What Firefox version are you using?
3. Could you share (privately by email, if you prefer) your NoScript Options>Export file?

**Comment by ib** [comment]
> Does the same problem persist in NoScript 11.2.8?

Yes. With 11.2.8 which I am currently using, the login also stops sometimes at bap.navigator.gmx.net without cookie warning (just a blank screen). This never happened with 11.2 or versions before (I cannot tell about 11.2.1 to 11.2.7).

I was updating from 11.2 to 11.2.8 and noticing some issues. I then tracked it down to the version change .3 to .4.

> What Firefox version are you using?

78.10.1esr (32-Bit)

> Could you share (privately by email, if you prefer) your NoScript Options>Export file?

Sure, I use your profile's email address.

**Comment by ib** [comment]
> With 11.2.8 which I am currently using, the login also stops sometimes at bap.navigator.gmx.net without cookie warning (just a blank screen).

This seems to be the bigger problem and it happens not only with GMX login.

I have a self-written local web application (HTML file with JavaScript) that loads Google maps (https://maps.googleapis.com/maps/api/js) using "defer". By default file:// and maps.googleapis.com have no script permissions. When I load the page and then assign "trust temporarily" to file:// and maps.googleapis.com, it often happens that nothing happens, i.e. the page remains empty and the NoScript icon continues to show the default icon (where script is forbidden). After closing the tab and opening the file again in a new tab, everything suddenly works as expected.

Previous versions (before 11.2.4?) always reloaded correctly immediately after changing permissions.

**Comment by ib** [comment]
Still present in 11.2.9.

**Comment by ib** [comment]
Still present in 11.2.10.

This can be easily tested. Just create an email account on gmx.de and log in a few times now and then. It does not happen every time, but most of the time.

**Comment by ib** [comment]
Still present in 11.2.11.

**Comment by hackademix** [comment]
Unfortunately an old gmx.de I used for testing has been disabled and it seems I cannot register a new gmx.de account because I don't have a mobile phone from Germany, Switzerland or Austria. 
Could you please register one for me (noscript@gmx.de seems to be available) and send me the credentials?

Also, are both problems (the [second one]( #issuecomment-860857533) may very well be a different issue) reproducible on Firefox 90 or above?

Thanks!

**Comment by ib** [comment]
> Also, are both problems reproducible on Firefox 90 or above?

I could not reproduce the gmx issue with Firefox 90 on a notebook. Since I normally use Firefox ESR, I guess I'll just wait for the next ESR.

**Comment by ib** [comment]
Seems to have gone in the meantime.
