### ISSUE TITLE
Add Google's recaptcha.net to the default allowlist

### ISSUE THREAD

**Issue by iam-py-test** [hackademix/noscript#200]
recaptcha.net is a domain used by Google for its Recaptcha service.
Because it is not on the default allowlist, it is blocked & CAPTCHA are blocked.
Due to its wide use, this breaks websites.
It would be nice if this was allowed by default, so users don't have to manually allowlist it for every install.

Example website: VirusTotal after enough queries that it starts to think your a bot

I am not sure if you accept this, but thought I should report it if you do.
Thank you for all your hard work on NoScript! It has saved by computer from real dangerous malware many times.

**Comment by KOLANICH** [comment]
No, it must be added in the default blacklist. reCAPTCHA is malware and ransomware.

**Comment by iam-py-test** [comment]
> 
> 
> No, it must be added in the default blacklist. reCAPTCHA is malware and ransomware.

@KOLANICH I don't understand?
How is Google's reCAPTCHA ransomware? Or are you saying the site posted is ransomware.
Please explain

**Comment by KOLANICH** [comment]
>How is Google's reCAPTCHA ransomware? Or are you saying the site posted is ransomware.
Please explain

It is made the way to either force people into surrendering their privacy and security by allowing Google to execute own-chosen code using browser-fingerprinting techniques on their devices, or discriminate against them on all the websites where reCAPTCHA is used to restrict access to functionality. So the data Google collects is the "ransom". It is not in a form of money, but in form of data, which also has value.

Also reCAPTCHA is loaded automatically in the browsers on default configurations, though I as a PC operator don't authorize scripts using browser fingerprinting other than free open source research ones to be run on my hardware.

**Comment by iam-py-test** [comment]
@KOLANICH I agree with your privacy concerns, but until sites realize Google and reCAPTCA are evil,  blocking them makes using the web harder.
Also, I would not call it ransomware, but I would call it spyware, which is what most Google-related things are

**Comment by iam-py-test** [comment]
@hackademix what is your opinion on this?

**Comment by iam-py-test** [comment]
I have reconsidered, and am closing this issue as invalid
