### ISSUE TITLE
Why does NoScript use encryption internally?

### ISSUE THREAD

**Issue by KOLANICH** [hackademix/noscript#203]
https://github.com/hackademix/noscript/blob/984e68e3cf2dc3c9446b608484c4c1bab6f544a6/src/bg/LifeCycle.js#L105-L109
https://github.com/hackademix/noscript/blob/984e68e3cf2dc3c9446b608484c4c1bab6f544a6/src/bg/LifeCycle.js#L119
https://github.com/hackademix/noscript/blob/984e68e3cf2dc3c9446b608484c4c1bab6f544a6/src/bg/LifeCycle.js#L165-L180
https://github.com/hackademix/noscript/blob/984e68e3cf2dc3c9446b608484c4c1bab6f544a6/src/bg/LifeCycle.js#L34-L49

**Comment by hackademix** [comment]
The answer seems quite clear from the very source snippets you've referenced, but anyway.

NoScript's temporary permissions are kept strictly in volatile memory to prevent them from being leaked to permanent storage by accident and breaking incognito/private mode expectations.

This encrypt-store-reboot-retrieve-decrypt dance is meant to let temporary permissions survive NoScript automatic updates.

Automatic updates restart the extension (wiping out all its volatile status) but not the browser, and most users expect temporary permission to disappear only when the browser is shut down, not randomly (as you could not even notice an extension has been updated).

The only way I could devise (and believe me, I've think about it a lot) for a WebExtension to persist its status across its reboots without either leaking t to permanent storage, send it to a remote server or use a sidekick native application is storing it in a content tab just before shutdown and retrieving it back on startup, and that's what NoScript does unless you check the _Advanced>Revoke temporary permissions on NoScript updates, even if the browser is not restarted_ option. 

The obvious problem with this approach is that if the hosting content tab is somehow aware of this mechanism, it could theoretically read or even tamper with NoScript's permissions. Bad, uh?

Therefore NoScript encrypts its data before sending it to the content script for storage, saving only the encryption key in permanent storage for retrieval after restart.

All clear?

**Comment by KOLANICH** [comment]
Thanks for the info. It looks like a big perversion that one has to use such tricks in order to keep temporary permissions away from disk, IMHO. I guess there should just be an API for a storage that is never evicted to disk but survives extension upgrades within `storage` pref. Maybe `storage.private`, because it is somehow like "privatebrowsing", but within a single extension.

As a temporary solution it can be possible to develop an extension doing the same, to which data is transferred using message passing and advice to a user to install both. In this case the data is cleared only when the storing extension is updated. So, there may be no need to expose pages with the information they must never see.

**Comment by hackademix** [comment]
> As a temporary solution it can be possible to develop an extension doing the same, to which data is transferred using message passing and advice to a user to install both. In this case the data is cleared only when the storing extension is updated. So, there may be no need to expose pages with the information they must never see.

That's actually a good idea, thanks. I may give it a shot myself and publish it as a generally available service for any extension sharing the same problem. However it's gonna be even harder in MV3, where long-lived global status in service workers is not an option by design.

**Comment by KOLANICH** [comment]
>However it's gonna be even harder in MV3, where long-lived global status in service workers is not an option by design.

Manifest Version 3 is a backdoored spec, and de-facto requiring having such an antefeature as ServiceWorkers in order to use WebExtensions means that Mozilla has crossed red line and that their browser is malware. Not that I am surprised, it was pretty obvious that Mozilla is going the direction of doing nasty things driven solely by company shortest term survival (with no sources of own income a company will have to do everything that the one financing their operatiin requires) for a pretty long time.

Though I don't have a solution. They go this way because neither have they, because it is not our or their Internet, it is the property of the Master of Internet, which is currently Googlag.
