### ISSUE TITLE
Infinite script injection maxes out CPU

### ISSUE THREAD

**Issue by tlancina** [hackademix/noscript#205]
At this URL: https://github.com/Cleafy/sxkdvm/blob/master/boot.sh, this script seems to be getting injected into the page infinitely, causing high CPU usage: 
```(() => {
          let injectionId = "injection:7d82c3bb-3378-47d5-b08c-f9ecb18a82f8:38e218faa8abb55192287617a9e7682e769702a26897dba499c6b9fb319b187c";
          if (document.readyState === "complete" ||
              window[injectionId] ||
              document.URL !== "https://raw.githubusercontent.com/Cleafy/sxkdvm/master/enoch_rev2839_boot"
          ) return window[injectionId];
          window[injectionId] = true;
          try {
          
      let domPolicy = {"permissions":{"capabilities":["script","object","media","frame","font","webgl","fetch","ping","noscript","unchecked_css","other"],"temp":false},"unrestricted":true,"cascaded":false,"navigationURL":"https://raw.githubusercontent.com/Cleafy/sxkdvm/master/enoch_rev2839_boot"};
      let {ns} = window;
      if (ns) {
        ns.domPolicy = domPolicy;
        if (ns.setup) {
          if (ns.syncSetup) ns.syncSetup(domPolicy);
          else if (!ns.pendingSyncFetchPolicy) {
            ns.setup(domPolicy);
          }
        } ;
      } else {
        window.ns = {domPolicy}
      }
      
          } catch (e) {
            console.error("Error in DocStartInjection script", e);
          }
          return document.readyState === "loading";
        })();
```
        
`https://raw.githubusercontent.com/Cleafy/sxkdvm/master/enoch_rev2839_boot` is a URL I visited previously (I believe in the same tab).

It seems to be repeatedly running this part:
```
if (document.readyState === "complete" ||
              window[injectionId] ||
              document.URL !== "https://raw.githubusercontent.com/Cleafy/sxkdvm/master/enoch_rev2839_boot"
          ) return window[injectionId];
```

Here is the trace:       
![image](https://user-images.githubusercontent.com/804331/126226592-819a32c4-466b-4ac8-96a0-81161c0a6db8.png)
[Profile-20210719T134109.json](https://drive.google.com/file/d/1vU_nTHUoK51UnbDH_Ij77jUCmYzGcF0f/view)
       
I can confirm that pausing execution in the DevTools causes CPU usage to drop from 110% to 0, resuming causes it to go back up.

- This started happening in the last week or two.
- Restrictions are disabled globally (I have also observed it when they are enabled)
- NoScript 11.2.9
- Chrome Version 89.0.4389.72
- MacOS 10.15.4

Here is a forum discussion on this issue: https://forums.informaction.com/viewtopic.php?f=10&t=26382

I have the tab suspended and will leave it up for as long as reasonably possible if you have any questions/requests. 

Unfortunately I haven't noticed a particular pattern as to when this happens. It's usually my fans going crazy alerts me and then a non-active tab dies when I kill the two processes (NoScript and the tab).

**Comment by hackademix** [comment]
Could you please try unzipping [the attached file](https://github.com/hackademix/noscript/files/6861723/noscript-11.2.10rc1-dbg-chrome.zip)  and installing its destination directory as an unpacked extension?

about:extensions > turn on __Developer mode__, then __Load Unpacked__ and choose the directory.

Be sure you disable the "regular" NoScript, in order to use this debug version instead, and check if you can reproduce anymore.

Thank you!

[noscript-11.2.10rc1 Chrome/Brave/Edge](https://github.com/hackademix/noscript/files/6861723/noscript-11.2.10rc1-dbg-chrome.zip)

**Comment by tlancina** [comment]
@hackademix I have been using this since you posted it and haven't experienced the issue yet. I'm going to close this, and will let you know if there are any issues going forward. Thanks for the quick fix!
