### ISSUE TITLE
Disabling unrestricted CSS on script-enabled pages may interfere with scripts manipulating link media attributes during page loads.

### ISSUE THREAD

**Issue by hackademix** [hackademix/noscript#207]
I updated to `11.2.11` (from the Chrome store), restarted Microsoft Edge, and reverted the `unrestricted CSS` permission.

Here's a render of [GitLab.com](https://gitlab.com/explore):

![image](https://user-images.githubusercontent.com/3078885/127341590-4c1b310a-cb3e-4973-836a-686470996bff.png)

For comparison, with `unrestricted CSS`:

![image](https://user-images.githubusercontent.com/3078885/127341699-87638231-27cc-4b7b-9eec-0368715a8531.png)

I'm running Microsoft Edge `92.0.902.55 (Official build) (64-bit)`.

_Originally posted by @fefrei in https://github.com/hackademix/noscript/issues/204#issuecomment-888364797_

**Comment by hackademix** [comment]
Just to be sure, did you disable the unrestricted CSS (which is not recommended to be kept off on scripting-enabled sites due to the dubious cost-benefit ratio) on purpose, or does it get disabled automatically on each update or new install (which would be a different bug in itself?).

Anyway, this specific issue should be fixed in [11.2.12rc1](https://github.com/hackademix/noscript/releases/tag/11.2.12rc1), to be installed as an unpacked extension until 11.2.12 reaches the stores.

**Comment by fefrei** [comment]
I don't recall ever touching this setting, and my NoScript install is rather recent (as I was moving to the Chromium-based Microsoft Edge) – so while I cannot guarantee it, I'm pretty sure this was disabled either by default or after an update. (But it did not turn off by itself again after my comment in #204 – I would have noticed as I use GitLab daily.)
