### ISSUE TITLE
NoScript seems to be completely broken on Firefox 93.0

### ISSUE THREAD

**Issue by BloodyMess** [hackademix/noscript#215]
After letting Firefox be updated to v93.0, NoScript (v11.2.11) is completely non-functional. Scripts are not blocked at all on any site, and the NoScript menu is empty except for the four large icons in the top left and right corners of the menu:
![NoScriptBroken](https://user-images.githubusercontent.com/12903370/138431935-448b03a6-85dd-44e5-b096-e8f6c713614a.jpg)

I'm running elementaryOS 5.1.7 Hera

**Comment by hackademix** [comment]
Hello, 
It's working fine here up to Nightly.
Probably something went wrong in the Firefox update.
Do the visible button works?
If they do, could you open the NoScript Options page and use first the [Export] then the [Reset] buttons?

**Comment by BloodyMess** [comment]
No, none of the buttons in the menu work. I had to get to the options page through the add-ons management page and choosing "preferences" in the menu for the NoScript add-on.

Is the Export button supposed to bring up a save dialog? I press it and nothing happens.

Also, when I select the Per-Site Permissions, all I get is the spinning indicator overlaid on the "Search or add a website" controls:
![Screenshot from 2021-10-22 03-51-23](https://user-images.githubusercontent.com/12903370/138442207-48ceb623-fea4-4f21-a8c6-67e97d1b7f0c.png)

**Comment by hackademix** [comment]
> No, none of the buttons in the menu work. 

It looks like the profile (or at least the extensions folder) is corrupted.

Are there other malfunctioning extensions?

Could you try uninstall and __then__ reinstall NoScript?

**Comment by BloodyMess** [comment]
OK. I uninstalled and then reinstalled it. That seems to have fixed it.
