### ISSUE TITLE
Trust is not always persistent

### ISSUE THREAD

**Issue by Eschryn** [hackademix/noscript#216]
When I press Trusted on some website and restart my computer and visit that site again it's not trusted anymore

**Comment by ServerWrestler** [comment]
What OS / Browser, and noscript version?  Do you still have the issue?  FWIW it appears functional for me on the latest stable Firefox on Windows.

**Comment by mrx23dot** [comment]
Try cleanly exit the browser, wait for browser processes to finish then reboot.
If works please close issue.

**Comment by Eschryn** [comment]
I haven't experienced this issue in a long while. I  will close this issue as it seems that no one else seems to be having it
