### ISSUE TITLE
an "http:" site entry is displayed as "http://http:"

### ISSUE THREAD

**Issue by bughit** [hackademix/noscript#22]
![image](https://user-images.githubusercontent.com/895588/45268395-7991a300-b449-11e8-81a3-a5d6e98adac8.png)

Also, what is the full syntax for these host/url patterns?

**Comment by hackademix** [comment]
That's the Tor Browser, right?
Protocol-only is supported only unofficially, and set by the Tor Browser's security slider as a mean to block everything on non-secure sites in blacklist mode.
It was not meant to surface in the UI, however commit https://github.com/hackademix/noscript/commit/050aa8b83bf83b83ce76bf69112f4fd29b732ba8 fixes this.

The syntax, from wide to narrow, is either 

- just protocol, or 
- domain (matches subdomain, too; restricted to match https: URLs only if prefixed with "§:")
- origin (protocol://hostname)
- full URL (protocol://hostname/path)

**Comment by bughit** [comment]
> restricted to match https: URLs only if prefixed with "§:"

Did you mistype that by any chance? That's extended ASCII 167, and it's not accepted by the prefs ui

Since multiple entries can match, which one wins?

**Comment by hackademix** [comment]
> That's extended ASCII 167, and it's not accepted by the prefs ui

It's not meant to be typed, but to mark entries internally. You switch it from the UI by toggling the red/green lock.

> Since multiple entries can match, which one wins?

The most specific (the one with the longest path, if overlapping, usually).
