### ISSUE TITLE
Content Security Policy script-src-attr

### ISSUE THREAD

**Issue by Sylry** [hackademix/noscript#220]
When i have an anchor (fragment) "#" in the url, the scripts are not executed on the page even though the scripts are authorized on this domain.

It works great when the anchor is not in the url at the loading of the page, it appears only if i go to an url containing an anchor (#something) directly, but not if i click an anchor on a page loaded without the fragment

In the console, there is this message:
> Content Security Policy: L’analyse de « script-src-attr » a échoué, car la directive est inconnue.

It is recent: a few days ago, it did not appears

**Comment by hackademix** [comment]
Does it happen in a clean profile with just NoScript installed?

**Comment by Sylry** [comment]
It seems it does not happen with a clean profile with just noscript nor with the other extensions I use.

I don't know if it is linked to, but on every page, i have an error message in the console: l.256 of moz-extension://c68b65a2-1534-4a65-9830-7b5108f77777/nscl/common/SyncMessage.js
> syncMessage error in https://example.org/: A network error occurred. (response )

This uuid does not seem to be an uuid of an extension i have, but the message is not here if i disable noscript extension

**Comment by jtotht** [comment]
The path does seem to be NoScript ([nscl/common/SyncMessage.js:256](https://github.com/hackademix/nscl/blob/3dea24a67007b06e0750ee54f5a851f235348e4b/common/SyncMessage.js#L256)). To make sure, you can open extension://c68b65a2-1534-4a65-9830-7b5108f77777/manifest.json (i.e. the path after the UUID replaced with `manifest.json`), and you should see `"name": "NoScript"` there. (This UUID seems to be an internal one, assigned by your Firefox instance, not the developer or addons.mozilla.org.)

**Comment by hackademix** [comment]
It's most likely an instance of [this issue](https://forums.informaction.com/viewtopic.php?f=7&t=26490), fixed in 11.2.14.
Please confirm and close, if that's the case.

**Comment by Sylry** [comment]
yes update to 11.2.14 fixes it, many thanks!
