### ISSUE TITLE
Application broken and not in Chrome store anymore?

### ISSUE THREAD

**Issue by leandroroser** [hackademix/noscript#221]
Hi guys, yesterday noscript stopped working and tried to reinstall it, but cannot find the extension on Chrome store. Is this an expected behavior?

Thanks,

   Leandro

**Comment by marktani** [comment]
It's a known issue, here is a good summary: https://www.bleepingcomputer.com/forums/t/768079/hackademixs-noscript-extension-broken-with-fix/

summary:

> The dev has identified a problem with a recent Chrome change that broke his new update. When he tried to unpublish the new version on Google Play, it caused the NoScript page to disappear there. He has provided a fix. He is working on 11.2.18 and will get that published ASAP.
>
> Basically, the problem is that the extension (and, I imagine, other extensions that rely on access to file URLs) ceases to work correctly, causing websites to not be fully functional, although they may display (Gmail won't load if you try to open the page - it gets stuck loading, the MBAM forum will load but you won't be able to post and stuff, etc.). You should disable the extension and skip to #5 before re-enabling it. If that doesn't work, you'll have to remove and reinstall it.
>
> He has provided a download to this version https://github.com/hackademix/noscript/releases/tag/11.2.16

**Comment by BastienDurel** [comment]
11.2.18 works, but settings are lost because the id is not the same :(

**Comment by LaughterOnWater** [comment]
When installing 11.2.18 in developer mode from "Load Unpacked" I get this error:
[NoScript] Cannot collect noscript activity data Error: Could not establish connection. Receiving end does not exist. Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.

**Comment by hackademix** [comment]
> When installing 11.2.18 in developer mode from "Load Unpacked" I get this error: [NoScript] Cannot collect noscript activity data Error: Could not establish connection. Receiving end does not exist. Could not establish connection. Receiving end does not exist. Error: Could not establish connection. Receiving end does not exist.

You can safely ignore that message, which just means that the current tab (the extensions panel) is a privileged one and cannot be accessed by NoScript.

Closing this issue, as NoScript is back on the Chrome Store. Thanks for your support and your patience.
