### ISSUE TITLE
Trust-settings interface doesn't work with local files (FF78)

### ISSUE THREAD

**Issue by Zapeth** [hackademix/noscript#227]
I don't know when this stopped working (sometime after December 2021?), but I'm unable to open the trust-settings interface when having a local html file with javascript open, neither the menu button nor the context menu work (the latter just opens a window that immediately closes).

This forces me to manually add an exception in noscript every time I open a different local file (I usually just temporarily allow them, since they are just temporary files in most cases).

This is on Firefox 78.15.0esr, dont know about newer/other versions.

**Comment by hackademix** [comment]
It's most likely a regression introduced in 11.3 (just a few days ago) and fixed in 11.3.2. 
Please check and, if confirmed, close, thanks.

**Comment by Zapeth** [comment]
Indeed it works again with 11.3.2 (extension wasn't automatically updated yet), thanks!
