### ISSUE TITLE
display full hostname including subdomain (perhaps in tooltip)

### ISSUE THREAD

**Issue by pawciobiel** [hackademix/noscript#230]
[feature request]
As a user I'd like to be able quickly see which subdomains of AWS/cloudflare/your fav CDN are being blocked. One side can sometimes use multiple subdomains/buckets on the same CDN provider and it would help if I could see which ones are actually being blocked. 
Itt may be enough to display tooltip when mouseover on a host name, eg: "...xyzcdn.com" -> "abc-def.xyzcdn.com"

**Comment by hackademix** [comment]
NoScript Options>Appearance>List full addresses in the permissions popup

**Comment by pawciobiel** [comment]
@hackademix excellent! somehow I've missed that. Thank you for all your work.
