### ISSUE TITLE
UI incongruence when switching on the "Vintage Blue" style [v11.4.1] [Firefox 98]

### ISSUE THREAD

**Issue by Felipe9999** [hackademix/noscript#234]
When switching on the (vastly superior in my opinion) "Vintage Blue" style, most icons get reverted to their previous look, however the NoScript icon on the right click menu remains unchanged, which is not supposed to happen.
![image](https://user-images.githubusercontent.com/70220216/160212151-c5cb631e-4195-49f6-8de3-1c18ed5a4a81.png)

**Comment by hackademix** [comment]
Unfortunately there's [nothing we can do about it](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create#sect1).

**Comment by Felipe9999** [comment]
oh ok

**Comment by jtotht** [comment]
> Unfortunately there's [nothing we can do about it](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/menus/create#sect1).

Except for campaigning about it. NoScript is maybe popular enough to have an influence on what browsers support. Having a consistent UI seems to be a valid use case.
