### ISSUE TITLE
Firefox ignores requests to open a webpage

### ISSUE THREAD

**Issue by sclaes** [hackademix/noscript#241]
Sometimes when I enter an URL in the address bar, Firefox completely ignores this and refuses to open the webpage (the URL of the previous loaded webpage reappears in the address bar and nothing happens). There is no problem with my internet connection because I can open the webpage in a new tab (i.e. when there is a link to that webpage on another webpage I can right click on it and open the webpage in a new tab).

This only happens when the NoScript extension is active.

I have no idea if this is relevant but I have many, many tabs open on a lot of windows.

**Comment by primalmotion** [comment]
I have the same issue with my searxng instance set as a default search engine. When noscript is enabled, and I have an opened webpage, typing a search query in the url bar (which would normally leave the current page and go to my searxng instance to show me the results) just does nothing. It stays on whatever page is opened. This does not happens when I search from a privileged page. Only from an actual webpage.

**Comment by hackademix** [comment]
Could you try removing any "Always block" line from _NoScript Options>Advanced>Sanitize cross-site suspicious requests_?

**Comment by primalmotion** [comment]
I tried that already (and just retried for good conscience) but that does not fix the problem

**Comment by primalmotion** [comment]
I mean I tried to uncheck `Sanitize cross-site suspicious requests` but I don't see 'Always block' anywhere

**Comment by hackademix** [comment]
Should it happen again, could you please click _about:debugging>This Firefox>NoScript>[Inspect]_ and check the ```Console``` tab for error messages related to the URL you can't open? Thanks.

**Comment by primalmotion** [comment]
I just tried that, and reproduced the issue while the console was open but I don't see anything relevant

![screenshot-2022-09-07-14:39:17](https://user-images.githubusercontent.com/208711/188987317-21882843-a892-425e-85f9-d08827153e85.png)

**Comment by primalmotion** [comment]
I also tried to disable all extensions but noscript to make sure there's no interference, but with just noscript, the problem still happens

**Comment by hackademix** [comment]
Could you please check whether the problem goes away with 11.4.11rc1 from https://noscript.net/getit#devel ?

Thanks!

**Comment by primalmotion** [comment]
Hum firefox does not want to install it.. it's weird because I installed 11.4.10rc3 yesterday :/

**Comment by hackademix** [comment]
> Hum firefox does not want to install it.. it's weird because I installed 11.4.10rc3 yesterday :/

Sorry, there was a problem with the crypto signature. Please retry now.

**Comment by primalmotion** [comment]
cool that works now and it seems to fix the issue!

**Comment by hackademix** [comment]
Thanks for reporting and testing.
