### ISSUE TITLE
Transifex | Request of addition of support for locale

### ISSUE THREAD

**Issue by Ricky-Tigg** [hackademix/noscript#242]
**noscript v.**.: 11.4.5 | Hello. Localization is [supported](https://noscript.net/community/)! I discovered it recently despite i had been aware of the existence of this product almost since its first release for Firefox. "_NoScript is currently localized in 28 languages_". According to an up-to-date-source, [Transifex](https://www.transifex.com/otf/noscript/) itself, the number of locales, for which this project's translation strings have been partially or fully translated, is higher. My locale, **Finnish**,  is not yet represented as supported. Could it be soon? I start investigating here and hope that this platform is the right place to request its addition. Regards.

**Comment by hackademix** [comment]
Hello, thank you for your will to contribute. 
You jhust need to [create a free Transifex account](https://www.transifex.com/signup/)  and join the translators at https://www.transifex.com/otf/noscript/

**Comment by Ricky-Tigg** [comment]
The following steps appeared to be involved in the **complete methodology** aiming to make a contribution to translation, operational, here according to the chronological order:

1. Account opening;
2. Requirement check | The locale intended to be requested is supported and then present [there](https://www.transifex.com/explore/languages/%5D/); Locale assumed present:
3. Request an addition of the option associated to a supported language assuming that one is not yet added:
4. Request made at previous step is entering a pending state for approval;

The highest rank of step currently reached by that request, is the **fourth**. Who knows how long it will take to the Transifex's administration to validate it? Eventually the process would keep on going as follows:

5. Eventually the previous request would be approved;
6. Request for_ joining a project translation_;
7. Request made at previous step is entering a pending state for approval;
8. Eventually the previous request would be approved.

**Comment by Ricky-Tigg** [comment]
The following steps according to the chronological order, appeared to be involved in the complete methodology aiming to make a contribution to translation, operational::

1. Account opening;
2. Requirement check | The locale intended to be requested is supported and then present there; Locale assumed present:
3. Request an addition of the option associated to a supported language assuming that one is not yet added:
4. Request made at previous step is entering a pending state for approval;
5. Previous request approved;
6. Request for joining a project translation;
7. Request made at previous step is entering a pending state for approval;
8. Previous request approved.

The highest rank of step currently reached by that request, is the **fourth**. According to my investigation at Transifex, the **organization's administrator** is the unique person that has power on the operation that takes place at step _5._ while the **organization's administrator**, the **team manager** for a specific team and the **language coordinator** for a specific locale, have power on the operation that takes place at step _8._. Details covering roles are in [documentation](https://docs.transifex.com/teams/understanding-user-roles). The current **valid** request involves _Finnish (fi_FI)_ alone.

**Comment by Ricky-Tigg** [comment]
The following steps according to the chronological order, appeared to be involved in the complete methodology aiming to make a contribution to translation operational:

1. Account opening;
2. Requirement check | The locale intended to be requested is supported and then present there; Locale assumed present:
3. Request an addition of the option associated to a supported language assuming that one is not yet added:
4. Request made at previous step is entering a pending state for approval;
5. Previous request approved;
6. Request for joining a project translation;
7. Request made at previous step is entering a pending state for approval;
8. Previous request approved.

The highest rank of step currently reached by that request, is the **fourth**. According to my investigation at Transifex, the **organization's administrator** and the **maintainer of the project** that I want the locale option to be added, have power on the operation that takes place at **step _5._** while the **organization's administrator**, the **team manager** for a specific team and the **language coordinator** for a specific locale, have power on the operation that takes place at **step _8._**. Details covering roles are in [documentation](https://docs.transifex.com/teams/understanding-user-roles). The current valid request involves _Finnish (fi_FI)_ alone.
