### ISSUE TITLE
Per site linked domains block

### ISSUE THREAD

**Issue by entryb** [hackademix/noscript#246]
Would it be possible to add feature to block a domain only when its accessed as a resource for a certain site?
The way its now if block a domain, its blocked when accessing all sites that try to request that domain.
Challenge with this is certain domain might be required for some sites and not for others so completely blocking it is not an option.

**Comment by hackademix** [comment]
How does this differ from [contextual policies](https://noscript.net/usage/#contextual-policies)?

**Comment by entryb** [comment]
Didnt see that one
