### ISSUE TITLE
The "Cross-tab identity leak protection" feature is causing my GitHub to lose login status in some cases

### ISSUE THREAD

**Issue by ghost** [hackademix/noscript#257]
The following text uses Google Translate

Steps to reproduce the problem:

1. Search GitHub on Google.
2. Use the middle mouse button to open the search results.<img src="https://i.imgur.com/H2tFbqK.png" style="zoom: 67%;" />
3. NoScript pops up this window, I just select "OK". <img src="https://i.imgur.com/nltN3a6.png" style="zoom: 67%;" />
4. After jumping to GitHub, it says I'm not logged in.

If you open a 404 page on GitHub in step 2, it will look like this: <img src="https://i.imgur.com/EIj2Ls5.png" style="zoom:50%;" />

If I click on the "Sign in" button pointed to by the red arrow, it will look like this: ![](https://i.imgur.com/GOAgk1v.png)

-----

Environment:

Firefox: 103.0.2
NoScript: 11.4.9

**Comment by hackademix** [comment]
Just follow any "real" link from the Github page (not AJAX stuff) and you should be able to login.
Otherwise, don't use "Load anonymously" when you know you want to be logged in and you trust the origin site.

**Comment by ghost** [comment]
> Just follow any "real" link from the Github page (not AJAX stuff) and you should be able to login. Otherwise, don't use "Load anonymously" when you know you want to be logged in and you trust the origin site.

I see, it seems that I misunderstood the function, thank you for your answer
