### ISSUE TITLE
Improve UI understability

### ISSUE THREAD

**Issue by unobatbayar** [hackademix/noscript#262]
Thank you so much for creating NoScript!

I'm a long time user. However, I've been struggling to understand the meaning of the icons and been very difficult to know what's going on even with the hover texts. Is it possible to update/replace these icons with just texts or even a simple ON/OFF toggle?

<img width="610" alt="Screenshot 2022-09-21 at 6 07 04 PM" src="https://user-images.githubusercontent.com/38866249/191463862-2e079f05-1e60-460b-ad5a-fb6a162400c5.png">

I'm happy to fix this myself and create a pull request.

Thank you. 

Please advise.

**Comment by hackademix** [comment]
Did you try _NoScript Options>Appearance>High Contrast_?

**Comment by unobatbayar** [comment]
No. How do you go to Options?

**Comment by unobatbayar** [comment]
Almost every button is an icon...

**Comment by hackademix** [comment]
> How do you go to Options?

From the popup, it's the third button from the left (<img src="https://noscript.net/img/ui/noscript-options.png"  width="32" height="32" alt="NoScript Options button">) or ```ctrl+O```.


> These icons are the main problem for me. What do they mean? 

[Explained here](https://noscript.net/usage/#trust-levels)

**Comment by unobatbayar** [comment]
Thank you. Sorry for this issue.

High Contrast solved my problem.
