### ISSUE TITLE
revoke temp permissions button and set all temp permissions changed place?

### ISSUE THREAD

**Issue by Jon-guy30** [hackademix/noscript#277]
Hi all! Am I going crazy or did the revoke temporary permissions button and the set all temp permissions buttons change place?! I swear the revoke button used to be on the right and the set all one on the left! 

Was it always like that 'cause I don't see anything in the changelogs? Strange thing is NS on Firefox for Android has the buttons like described above. 

I was confused since I clicked on the left button to set permissions and it revoked them, I don't recall it doing that.

Please tell me was it always like this? 

If they did change place, the previous layout was more intuitive for me at least.

**Comment by hackademix** [comment]
No, they've not been swapped indeed. 
You may have swapped them accidentally by drag & drop, though, as the button ordering can be customized that way.

**Comment by Jon-guy30** [comment]
Yeah, I noticed just now. I must have moved it accidentally with my mouse. I promptly moved it back.  Thanks for the reply.
