### ISSUE TITLE
Allow deleting of site policy

### ISSUE THREAD

**Issue by QazCetelic** [hackademix/noscript#278]
I would like to remove a policy from the list, however I can't find how to do this.

![image](https://user-images.githubusercontent.com/51381523/217586567-7257a401-e33e-482a-ba31-028d880f637e.png)

I think it would be useful to have the option to remove a single policy or add a delete icon next to an entry if a feature like that already exists.

**Comment by hackademix** [comment]
Turning it to "DEFAULT" is exactly the same as deleting the policy: no site data, indeed, is store for DEFAULT entries, and as soon as you reload the per-site permissions page you'll see they're actually gone.,
