### ISSUE TITLE
Option for auto-allowing current domain

### ISSUE THREAD

**Issue by crazydef** [hackademix/noscript#280]
NoScript is great, but the one thing that's really (really) bugs me is why doesn't it auto-enable scripting for the current domain I'm visiting?

Or at least give me an option so I can enable that myself.

I..e, if I'm visiting MyAwesomeSite.com why can't I let MyAwesomeSite.com (and only that domain) be trusted automatically?

**Comment by hackademix** [comment]
Isn't this `NoScript Options>General>Temporarily set top-level sites to TRUSTED`?

**Comment by crazydef** [comment]
Doh.
Yes, yes it is.

I can't believe I missed that.  I just spent five minutes going through the settings to make sure it didn't exist too.
