### ISSUE TITLE
Is Temp. TRUST not to be exported?

### ISSUE THREAD

**Issue by nasheayahu** [hackademix/noscript#302]
I need to be able to save and export Temp. TRUST settings as well, is this the default not to save them?

**Comment by hackademix** [comment]
Correct, temporary permissions are not included in the exported JSON.

A way to work around this would be using`NoScript Options>Advanced>[x] Debug` and looking for "temp" items in the box (which is read/write - be careful not to accidentally break your settings!)

**Comment by nasheayahu** [comment]
Okay I found this,

`"temp": [
      "§:datatables.net",
      "§:adobedtm.com",
      "§:statuspage.io",
      "§:trustarc.com",
      "§:unpkg.com"
    ]`

do mean I would have to either save the whole Json to a different file or just this portion and add it back in after I do a import?  Also it would be nice to add a setting giving the user the option to keep Temp. TRUST.  Could this be added to your next release?

**Comment by hackademix** [comment]
>  I would have to either save the whole Json to a different file

Copying the whole JSON in a file and pasting it back later in the same text area is roughly equivalent to an export + import.

> Also it would be nice to add a setting giving the user the option to keep Temp. TRUST. Could this be added to your next release?

Not the next, probably, but putting it in my TODO list.

**Comment by nasheayahu** [comment]
> Copying the whole JSON in a file and pasting it back later in the same text area is roughly equivalent to an export + import.

Will do...

> Not the next, probably, but putting it in my TODO list.

Sounds good, thanks......
