### ISSUE TITLE
`!presetName` is always a boolean

### ISSUE THREAD

**Issue by alex-kinokon** [hackademix/noscript#312]
https://github.com/hackademix/noscript/blob/45861afeaa3f9cad6f26f636d13181ec24b6accd/src/ui/ui.js#L1046

is missing a bracket

and

https://github.com/hackademix/noscript/blob/45861afeaa3f9cad6f26f636d13181ec24b6accd/src/bg/LifeCycle.js#L193

should be uppercase `Error`

**Comment by hackademix** [comment]
Fixed, thanks.
