### ISSUE TITLE
Partially operationnal | domain: askubuntu.com

### ISSUE THREAD

**Issue by Ricky-Tigg** [hackademix/noscript#323]
**Version:** 11.4.28 | **Browser**: Firefox | **Site:** https://askubuntu.com/

Hello. While all on this site is as _trusted_, the following elements are exhibited despite repectively a selection was done and close-cross was clicked.

![image](https://github.com/hackademix/noscript/assets/26058215/b53b385e-3111-4749-9312-b7c731a43f84)

![image](https://github.com/hackademix/noscript/assets/26058215/c39bbb18-a949-4b34-82f9-f0208e1d7fb9)

In order to get these elements hidden, the option _Disable restrictions for this tab_ must be enabled; not recommanded though.

**Comment by hackademix** [comment]
That's because it is shown statically by the page (no scripts involved) but dismissed through JavaScript.

A work around would be using mousedown+CANC to hide it.

**Comment by Ricky-Tigg** [comment]
I was unable to confirm that this workaround is functionnal; maybe by your combination you meant _a gesture_ + <kbd>a key</kbd>. No <kbd>Canc</kbd>-named key is present on my laptop's keyboard, nor mouse is available, so I have to rely solely on pad for gestures. Then to conclude, as demonstrated in report, these unwanted behaviors cannot be avoided other than by applying a non-recommended practise.

**Comment by hackademix** [comment]
Sorry, I overlooked me having an Italian keyboard.
I meant left-mousedown + DEL(ete).

**Comment by Ricky-Tigg** [comment]
I couldn't observe any more the initial behaviors since now this extension found the sstatic.net-named component that had to be as _trusted_ and provides the functionalities that were inhibited, thus allowing the reported elements to be hidden. Strange this inconsistent behavior. Closing though.
