### ISSUE TITLE
Dead project?  Issues dating back from 2018 and only updates in years are the copyright year update :-(

### ISSUE THREAD

**Issue by Kees1958** [hackademix/noscript#329]
I guess with the introduction of Manifest V3 this is a dead project,

**Comment by hackademix** [comment]
https://github.com/hackademix/noscript/commits/main

**Comment by Kees1958** [comment]
:-) Okay you fixed some reported bugs, have to give you credits for that.

Question is: does Noscript survive Manifestv3 (answer that an I will close the issue)

**Comment by hackademix** [comment]
>  Noscript survive Manifest V3

Yes. 

See also https://github.com/hackademix/nscl

**Comment by Kees1958** [comment]
:-) So I stand corrected thanks for answering (by the wat a happy user of Noscript, not as blocker in default block third-party, but as using as a script sniper to block unwanted third party)
