### ISSUE TITLE
Clarify what default restriction 'other' covers

### ISSUE THREAD

**Issue by leonklingele** [hackademix/noscript#33]
NoScript has options to allow the following media types by default:

- script
- object
- media
- frame
- font
- webgl
- fetch
- other

What exactly does 'other' cover? "Java", "Flash", "Silverlight", "Plugins"?

**Comment by hackademix** [comment]
"Java", "Flash", "Silverlight" and other plugins are covered by object.
"other" is any (possibly new) load type which is not included in the "known" ones.

**Comment by leonklingele** [comment]
Thanks for the clarification! :)
