### ISSUE TITLE
What is the Google Manifest V3 status?  

### ISSUE THREAD

**Issue by LennyFox** [hackademix/noscript#349]
Hi, not an issue for now, but for the near future.

**Will NoScript release a Mv3 version?**

**Comment by leoheitmannruiz** [comment]
Perhaps see #359

**Comment by LennyFox** [comment]
Thanks, that is helpfull

Op wo 18 sep 2024 om 01:46 schreef Leo Heitmann Ruiz <
***@***.***>:

**Comment by hackademix** [comment]
NoScript 12, [here](https://chromewebstore.google.com/detail/noscript/doojmbjmlfjjnbmnoijecmcbfeoakpjm).

![image](https://github.com/user-attachments/assets/3b98dcc2-36ba-46b3-bfd7-220adc2ea514)
