### ISSUE TITLE
Prevent duplicate synthetic placeholders for invisible capability probes

### ISSUE THREAD

**Issue by tiagoapimenta** [hackademix/noscript#369]
the new feature introduced on version 11.4.30 called "Best effort WebGL placeholders for offscreen capability detection" actually break the layout of several websites, including Google and Twitch.

![image](https://github.com/user-attachments/assets/1b40f92a-d0e5-41aa-8259-96e61265fff0)
![image](https://github.com/user-attachments/assets/e96603a7-49ea-4b37-8eff-60fb1d6960a2)
![image](https://github.com/user-attachments/assets/839faae9-9b07-49fe-8fa6-9e709731920f)

It's even worst for twitch player: https://player.twitch.tv/?channel=...&parent=twitch.tv
![image](https://github.com/user-attachments/assets/c692e7e5-509d-419d-a7ed-4dc25bd962ac)

Please, add a settings to hide/show this placeholder, and preferable make it hidden by default.

**Comment by hackademix** [comment]
Thank you for this report.

Plan to fix it in 11.4.31:

1. Create only one synthetic placeholder per capability/page for blocked off-screen detection probes.
2. Make it smaller and fixed-positioned on the bottom left of the page.
3. Add a new _NoScript Options>Appearance>Show synthetic placeholders for invisible capability probes_ checkbox (on by default).

**Comment by hackademix** [comment]
Please check [11.4.31rc1](https://noscript.net/getit/#devel), which implements 1 and 2 above, thanks.

**Comment by hackademix** [comment]
[11.4.31rc2](https://noscript.net/getit/#devel) implements 3 too: please check, thank you.

**Comment by tiagoapimenta** [comment]
I tested and Confirm it's working as expected.

Now it appears only once in the bottom right:
![image](https://github.com/user-attachments/assets/ad18ce63-c40c-4b6a-b6b6-676c811cdb9d)

And when changed the settings it's vanished after the page is refreshed
