### ISSUE TITLE
Make 'globally allow' button a little bit more difficult to click

### ISSUE THREAD

**Issue by jimbobmcgee** [hackademix/noscript#37]
Found myself running without Noscript a couple of days ago, when I accidentally clicked the <kbd>S!</kbd> button instead of the <kbd>^!</kbd> button.

100% entirely user-error, but it would be nice if that global action was a little bit more difficult to do.  I was thinking:
 * *Either* moving the <kbd>S!</kbd> button to the options page (removing it from the popup menu)
 * *Or* adding a confirm dialog to the clicking of the <kbd>S!</kbd> button

Just an idea.  As I said, though, entirely my error, so feel free to point, laugh and discard!

**Comment by hackademix** [comment]
You can already customize NoScript's popup toolbar by dragging the button into the so called "buttons graveyard" (just start dragging to see it), therefore allowing users to implement your 1st suggestion by themselves, if they want. Therefore marking as WONTFIX for now.

**Comment by jimbobmcgee** [comment]
Works for me.  Thanks!
