### ISSUE TITLE
noscript setting icon disapear in firefox

### ISSUE THREAD

**Issue by brongniart** [hackademix/noscript#376]
Hello,

I have an issue with the setting icon disappearing in Firefox on Linux:

- When I install noscript before any configuration change, the noscript icon is visible:
![before-change](https://github.com/user-attachments/assets/1d1270ac-2cc7-4b14-b58c-a2ece08a173c)

- If I then change the history setting to "never remember" and restart:
![setting-change](https://github.com/user-attachments/assets/9261e69b-639f-4cab-a4d9-d27fafffb80a)

- Then the menu disapear:
![after-change](https://github.com/user-attachments/assets/34d1ab39-b0c5-4e25-8b66-79e30fb4ca95)

Note that if I reactivate the history: the icon is back.

I'm not sure if this is a Firefox or noscript bug. feel free to redirect me to Firefox if needed.

Thank

**Comment by hackademix** [comment]
Hello. `History>Never Remember History` is considered by Firefox equivalent to force every window to be in private browsing mode.

This means that only extensions already allowed to run in private windows are enabled/shown:

`Settings>Add-ons>NoScript>Run in Private Windows>Allow`
