### ISSUE TITLE
[chrome] tab crash on diffchecker.com with Noscript 11.4.38 and newer

### ISSUE THREAD

**Issue by pal1000** [hackademix/noscript#380]
![Screenshot 2024-09-20 220220](https://github.com/user-attachments/assets/b4b50534-4710-4d83-9678-6df1ce6a6adc)
![Screenshot 2024-09-20 220427](https://github.com/user-attachments/assets/51150c5d-0f69-45a0-8baf-5b4dfc9c02d6)
![Screenshot 2024-09-20 220520](https://github.com/user-attachments/assets/8666341e-d4f5-488f-9e44-ab73251c2e1a)

**Comment by hackademix** [comment]
Thank you for your report.

Have you got the `webgl` capability disabled in your TRUSTED preset?

**Comment by pal1000** [comment]
Yes.

**Comment by hackademix** [comment]
Then it's a Chromium bug which I've worked around in https://github.com/hackademix/nscl/commit/668bba9f3db9c51024a068d72af77a7ff480293c

You can check latest RC https://noscript.net/getit/#rc-for-chromium or wait for 11.4.39 (identical) to be approved by Google (I've submitted it yesteday to the Chrome store).
