### ISSUE TITLE
Naked domains with no HTTPS lock and/or explicit port numbers are not correctly matched in mapped MV3 DNR rules

### ISSUE THREAD

**Issue by l-404-l** [hackademix/noscript#387]
Not entirely sure of issue but everytime i try to use it with this update the extension crashes when i load my list (tried uninstalling and reinstalling) also seems to block localhost sites even if set to trusted

**Comment by hackademix** [comment]
Thank you very much for your report.

1. What format is your list using (could you share a sample)?
2. what do you mean by "local host sites"? literal http://localhost? with explicit port? explicit IPs? (sample?)

**Comment by l-404-l** [comment]
Tried it with a fresh list as well and it froze with literal http://localhost/? with explicit port example (http://localhost:5173/)

**Comment by BenAldebert** [comment]
I'm getting the same errors on localhost but also on other internet-facing sites that aren't owned by me. Some of the repeated console logs I get:

```console
Refused to load the script ... because it violates the following Content Security Policy directive: "script-src-elem 'none'".
Refused to load the font ... because it violates the following Content Security Policy directive: "font-src 'none'"
Refused to load media from ... because it violates the following Content Security Policy directive: "media-src 'none'".
```

All of these sites worked for me previously, and continue to work in browsers that don't have NoScript installed.

**Comment by hackademix** [comment]
Thank you for the additional information.

Those console messages should not be relevant as long as they start with "[Report Only]" (it's just the way NoScript checks for resources needed by the pages in this brave MV3 world).

Again, can you share your actual configuration?

Have you got other extensions (e.g. uBlock) which might interfere, and does the problem persist if you disable them?

Could you provide me with a internet-facing site to check?

Thanks!

**Comment by banthungprong** [comment]
Can confirm this. I use 10.0.0.0/24 as my local network. No local site (10.0.0.4:8080 for a Homer Dashboard as example) is working anymore when NoScript is active in Chrome - but still working in Firefox without problems.

**Comment by sdoh55** [comment]
Also confirming same issue reaching local websites. All my local services are unreachable via localhost and local IP address.

**Comment by SynapseScribe** [comment]
this update broke the whole fkn internet for me on brave. also why isn't there a release for this version in releases?
related to https://github.com/hackademix/noscript/issues/388

**Comment by hackademix** [comment]
This is fixed in [12.0.2](https://noscript.net/getit/#nonstore-versions-for-chromium), which is already in queue for approval on the Chrome store. Thank you for your reports.

**Comment by banthungprong** [comment]
Even with 12.0.2 not working. No local address is accepted (like Fritzbox URL 10.0.0.1 in my home). Cleared Cache etc, removed and reinstalled extension. Nothing working.

**Comment by hackademix** [comment]
> Even with 12.0.2 not working. No local address is accepted (like Fritzbox URL 10.0.0.1 in my home).

That's weird, because I've verified both domain names and IPs are working fine now.

Maybe there's some other edge case with your specific configuration:

1. Could you please share your _NoScript Options>Export_ file?
2. Does the problem persist if you disable the other extensions you've got, if any?

Thanks!

**Comment by banthungprong** [comment]
It is working now, I guess the mistake was not to add the complete IP (like 10.0.0.1 or 10.0.0.4). Just like before I uses 10.0.0 and that doesn't seem to work right now.
I wanted to add a "rule" to accept alle local IPs.

**Comment by Baeon** [comment]
whatever you did seems to have worked. thanks for the speedy fix
