### ISSUE TITLE
Noscript blocking in chrome even with "trusted" checked

### ISSUE THREAD

**Issue by Baeon** [hackademix/noscript#389]
when navigating to other computers on my network, even though "trusted" is enabled, noscript is blocking my ability to see the info on the web pages.... if i click"disable restrictions for this tab" i can see the pages. this is a recent development, have never had this issue before.

**Comment by Baeon** [comment]
just checked it on firefox, it doesnt happen there... trusted allows the pages to be seen

**Comment by hackademix** [comment]
Thanks for your report. 
It's a duplicate of #387.
