### ISSUE TITLE
Errors in v12.0.2 from manual install

### ISSUE THREAD

**Issue by mushu999** [hackademix/noscript#392]
https://imgur.com/a/l4YfZPR

Windows 10, 22H2 build 19045.5198
Chrome: Version 131.0.6778.86 (Official Build) (64-bit)

When you go to Chrome extensions and see the NoScript box there is an "ERRORS" button, click it and get a bunch of errors per the screenshot linked above. I did a manual install since it isn't available in the store yet. This was to fix the issue #388 bug. Note that the previous (interim) version 11.4.43.9002 had different (deprecation) errors in the Extensions screen.

**Comment by hackademix** [comment]
Those are expected and unavoidable, due to the hacks needed to work around Manifest V3's limitations.
