### ISSUE TITLE
MV3 Issues with Win 7 Chrome (Version 109.0.5414.120 (Official Build) (64-bit))

### ISSUE THREAD

**Issue by idpeters74** [hackademix/noscript#400]
Hello,

Not sure if anyone can help, but when no-script was updated to the 12.0.8 (MV3) I started having a lot of issues with websites not loading (google's "white page of death" kept appearing) or breaking in other ways that are hard to describe.  I went to the no-script page and downloaded version 11.4.44 (MV2) and all the issues went away.

I am one of those Luddites still using Windows 7 (64-bit).  The Chrome I am using is:  Version 109.0.5414.120 (Official Build) (64-bit)

Any help or fixes would be greatly appreciated so I can stay on the latest version of an extension I love.

**Comment by hackademix** [comment]
I'm sorry to hear that, but as we found elsewhere (the Kiwi Browser breakage - Kiwi being based on Chromium 124) supporting any browser based on Chromium < 128 on Manifest V3 is a minefield.

Your best bet is staying on 11.4.44 - which at this moment is on feature-parity with 11.5.x ("MV2.5" for Firefox) and 12.x (MV3 for latest Chromiums).

**Comment by jtotht** [comment]
If you care about security (as a NoScript user, you probably do), you should switch to Firefox – Firefox is the only popular browser to [still support Win7, for at least a few months](https://support.mozilla.org/en-US/kb/firefox-users-windows-7-8-and-81-moving-extended-support). (Or, even better, to a supported OS. Win7 is a great operating system, I loved and used it until days before the end of support, but without security updates for almost half a decade, it’s no longer secure.)
