### ISSUE TITLE
"fetch" option stopped other extensions from using XMLHttpRequest?

### ISSUE THREAD

**Issue by eight04** [hackademix/noscript#41]
There is an image downloader extension which uses XMLHttpRequest to get the image blob on the page. When `fetch` option was checked, the request failed. See https://github.com/eight04/image-picka/issues/150.

Is it possible to work around with this?

**Comment by hackademix** [comment]
This should be fixed by commit 83979c532e04c5afc53ecad25f6662ef7ae72874.

**Comment by hackademix** [comment]
Now in 10.2rc1, https://noscript.net/getit#devel

**Comment by hackademix** [comment]
Now in 10.2rc1, https://noscript.net/getit#devel
