### ISSUE TITLE
"Disable restrictions for this tab" doesn't work as expected under easily reproducible conditions.

### ISSUE THREAD

**Issue by musonius** [hackademix/noscript#48]
The function _"Disable restrictions for this tab"_ doesn't work correctly under certain conditions (see below): Activating _"Disable restrictions for this tab"_ does not disable restrictions for third-party sites, unless the option _"Temporarily set top-level sites to TRUSTED"_ is set or some other conditions are met (see below).

I have tested this bug with Firefox 63 and 64 with NoScript 10.1.9.9 and later on two computers running Windows 10. At the moment, I use Firefox 64 and NoScript 1.2.1.

The following steps are required to reproduce the bug:

1.  create a new profile in about:profiles and start Firefox using the new profile
2. install NoScript (from [addons.mozilla.org](https://addons.mozilla.org/de/firefox/addon/noscript/), for example)
3. visit a page which needs third-party scripts: I load the top-most article of [theguardian.com](https://www.theguardian.com/international) to reproduce the bug. The section **Most popular** at the end of the article needs *guim.co.uk* to work. The bug is reproducible for any other page with third-party sites.
4. set _"Disable restrictions for this tab_" and nothing happens after the automatic reload the page apart from disabling restrictions for the top-level site theguardian.com. Setting theguardian.com to "Temp. TRUSTED" loads guim.co.uk and the other third-party sites.

The bug does not occur under the following conditions:

1. the option _"Temporarily set top-level sites to TRUSTED"_ is set
2. the development tools of Firefox are displayed in the tab
3. other extensions like "uBlock Origin" or "HTTPS Everywhere" are running (installing an arbitrary second extension is not sufficient though: installing "TabWalk", for example, doesn't help)

Why displaying the development tools or installing certain additional extensions is sufficient for the bug to not occur, is a mystery to me. Activating the tracking protection of Firefox, by the way, does not change anything.

**Comment by musonius** [comment]
I have tested older releases to see when the bug was introduced. The last release where _"Disable restrictions for this tab"_ worked as expected was NoScript 10.1.9.8 (Oct 6, 2018) and the first one with the bug was NoScript 10.1.9.9rc1 (Oct 13, 2018). I think this should help you find the bug.

**Comment by hackademix** [comment]
The problem is with the cookie-based hack to communicate per-tab information, which cannot work with non-HTTP subframes (such the about:blank ones in your test page). The dev tools and other extension seem to  lock the frame loading so that the inherited cookie is read before it gets erased by the parent page, but this doesn't happen (nor is actually desirable) in normal conditions.
Also, the "old" name-based hack is not affected by this problem, but had serious issues of its own.
I'm afraid I must resort to yet some other sort of hack, possibly for subframes only...

**Comment by musonius** [comment]
Thanks for looking into the problem and your interesting analysis!

I thought about using NoScript as my only extension again and the behavior confused me quite a bit. This function is very convenient for me in certain situations, but at the end of the day the most important thing for me is to be sure that unwanted scripts are not executed.

Feel free to let me know, if I can test anything.

**Comment by hackademix** [comment]
Please check https://github.com/hackademix/noscript/releases/tag/10.2.2rc1, thanks.

**Comment by musonius** [comment]
Works like a charm for the test page and I have not seen any negative surprises so far. Thanks for the fix!
