### ISSUE TITLE
TypeError: document.documentElement is null DocumentCSP.js:24:1

### ISSUE THREAD

**Issue by musonius** [hackademix/noscript#51]
I get some error messages in my browser console:

```
TypeError: document.documentElement is null DocumentCSP.js:24:1

SyntaxError: redeclaration of let CSP CSP.js:1:1

[Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.addSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 65"  data: no]

[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.removeSheetUsingURIString]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/ExtensionCommon.jsm :: runSafeSyncWithoutClone :: line 65"  data: no]
```

Since I get the errors with a fresh profile of Firefox 64 (Windows 10) and NoScript 1.2.1, I don't think it's because of the changes for issue 48.

I can replicate the issue as follows:

1. create a new profile
2. set your start page and your new tab page to the blank page
3. set `browser.tabs.closeWindowWithLastTab` to `false` in about:config
4. install NoScript (I have tested version 1.2.1 and 1.2.2rc2)
5. start the browser with this configuration or close all tabs, such that there is just one tab with the blank page
6. I have to click X twice now, which is stupid, but that's how I get there most easily.
7. open and close the NoScript windows (the text regarding the privileged pages does not appear, if the bug occurs: the missing text is why I checked the browser console)

**Comment by hackademix** [comment]
Actually in order to reproduce you just need step 2 plus creating a new tab, and it's an instance of https://bugzilla.mozilla.org/show_bug.cgi?id=1491994
