### ISSUE TITLE
Nothing happens by default when selecting NoScript in context menu

### ISSUE THREAD

**Issue by scootergrisen** [hackademix/noscript#58]
When i right click a website and select NoScript nothing happens.
This seems to be the default behaviour.
Only if i customize Firefox and drag the NoScript icon to the menu bar will the NoScript area appear when i right click and select NoScript.
But since it is not there by default nothing will happen by default and this is confusing for new users i think.

Using Windows 7 and Firefox 60.4.0esr and NoScript 10.2.1.

**Comment by src-r-r** [comment]
Thank you for submitting an issue regarding NoScript. It's helpful that you listed your OS, Firefox version, and NoScript version.

Is this still an issue? This issue was filed in February and is a few Firefox versions behind. Just wanted to be sure.

**Comment by scootergrisen** [comment]
Still nothing happens with:
Firefox 71.0 (64-bit)
NoScript Version 11.0.9

Works if i customize Firefox and drag the icon to the menu bar.
Also works if i customize Firefox and drag the icon to the >> menu but then the area is small with horizontal and vertical scroll bars.

**Comment by hackademix** [comment]
Fixed in [11.0.10rc2](https://github.com/hackademix/noscript/releases/tag/11.0.10rc2), thanks.
