### ISSUE TITLE
Make sure NoScript is the last that modifies the request headers 

### ISSUE THREAD

**Issue by kkapsner** [hackademix/noscript#6]
Until https://bugzilla.mozilla.org/show_bug.cgi?id=1477696 is not solved you should make sure that NoScript is the last WebExtension that modifies the CSP-Headers.
Since you provide the most amount of protection your headers should be used. Also NoScript gets stuck in a reload loop if that's not the case: https://github.com/kkapsner/CanvasBlocker/issues/222

My suggestion is to remove and re-add the listener for onHeadersReceived on some interval (maybe every minute or so). This ensures that the NoScript-Listener is the last one called which wins if the headers clash (CSP headers only clash if the web site does not provide one by itself.

**Comment by hackademix** [comment]
Looking into that, thanks. It's less simple than it seems, because listeners registration is asynchronous too and the risk is losing some requests when re-adding the listener, but I think it can be worked around by installing overlapping listeners (watching for duplicate calls) and removing the older one from the new one. Unfortunately we keep stockpiling complexity & hacks, though :(

**Comment by kkapsner** [comment]
Yes - the transition to WebExtensions is still ongoing and rough...

The usage of CSP in CanvasBlocker is also just a hack: https://bugzilla.mozilla.org/show_bug.cgi?id=1475831
I would gladly get rid of it.

Thanks for checking.

**Comment by hackademix** [comment]
Please check https://github.com/hackademix/noscript/releases/tag/10.1.8.17rc2 thanks.

**Comment by kkapsner** [comment]
Hm... I'm not quite sure if it all works. I still get the CB CSPs but the infinite reload gets broken at some time.

My scenario:
1. install RC
2. deactivate CB
3. reactivate CB
4. open any page that is not trusted in NoScript and look at the console

**Comment by hackademix** [comment]
Please check [10.1.8.17rc4](https://noscript.net/getit#devel), thanks.

**Comment by kkapsner** [comment]
Looks good. I'm not able to get the CB CSPs any more.

Thanks for the fix.
