### ISSUE TITLE
Non localized string?

### ISSUE THREAD

**Issue by Diklabyte** [hackademix/noscript#7]
In `src/ui/options.html` is an unlocalized string.
Is this intended, or fall into oblivion?

https://github.com/hackademix/noscript/blob/5e1a1782132e9a7c2e01a25eefbf7bce4d805c0d/src/ui/options.html#L19-L21

I expected a localized string like `__MSG_OptionsLong__`.

**Comment by hackademix** [comment]
[Fixed, thanks](https://github.com/hackademix/noscript/commit/2990ca5f2c1aaf7c5b31df035412038e55c64cb7).
