### ISSUE TITLE
Adding class="mozwebext" to webpages make user easy to be tracked

### ISSUE THREAD

**Issue by tiansh** [hackademix/noscript#80]
I'm not sure what's going wrong. But I just noticed that with this extension installed, it add className `mozwebext` to every webpage. But, why? It makes website possible to test if user is using noscript which persionally don't like to be happen.
[A quick search on GitHub](https://github.com/hackademix/noscript/search?q=mozwebext&unscoped_q=mozwebext) suggests me that this className is used for config page. If I understand correctly, this should only happened to option page but should be avoid from normal web pages. So maybe this extension should change the injection of className to somewhere else.

**Comment by hackademix** [comment]
You're right, that was a bug. Just fixed, thanks.
