### ISSUE TITLE
NoScript cannot prevent webpages from using WebGL

### ISSUE THREAD

**Issue by KOLANICH** [hackademix/noscript#9]
I have noticed that webpages (I have tested on https://openjscad.org/) have access to WebGL even if it is not allowed in NoScript.

**Comment by hackademix** [comment]
I couldn't reproduce this. Tested on NoScript 10.1.8.16 with Firefox 62b for Android, as I'm traveling ATM. CUSTOM preset cloned from TRUSTED, with webgl unchecked. Which NS/Fx versions you using?

**Comment by KOLANICH** [comment]
I have spotted it 2018-07-02 , so the version of NS by the date was  10.1.8.2  and the relevant FF devedition version by the date (sorry, haven't found ff devedition history). Cannot check for now - webgl doesn't work at all on the device I currently use. Gonna check on Monday.

**Comment by KOLANICH** [comment]
Have checked now. By now it works.
