### ISSUE TITLE
Security and Privacy Info

### ISSUE THREAD

**Issue by KlausEverWalkingDev** [hackademix/noscript#95]
I suggest create an option to automatically have a service of this page choosen (or directly linking to it when you click the resources' main domain). As I only use the "http://www.wmtips.com/tools/info/?url=" (Webmaster Tips Site Information) option, it's a waste of time landing on Security and Privacy Info. I can make clearer if my English was not that proper. ^_^'

**Comment by frankclaassens** [comment]
+1

It's bad practice to redirect to your page, especially because its very easy to log the IP address through httpd logs.

My suggestion would be to add a new textfield to options page which allows a single URL, defaulted to: http://www.wmtips.com/tools/info/?url=

This should be priority.
